/**
 * Emoji Data Module
 * Comprehensive emoji dataset with categories, search index, and metadata.
 * Inspired by Canva and Adobe Express emoji picker patterns.
 */

export interface EmojiEntry {
  emoji: string
  names: string[]
  category: EmojiCategory
  skinTones: string[]
}

export type EmojiCategory =
  | 'smileys'
  | 'people'
  | 'nature'
  | 'food'
  | 'activities'
  | 'travel'
  | 'objects'
  | 'symbols'
  | 'flags'

export interface EmojiCategoryMeta {
  key: EmojiCategory
  label: string
  icon: string
}

export const EMOJI_CATEGORIES: EmojiCategoryMeta[] = [
  { key: 'smileys', label: 'Smileys & Emotion', icon: '😀' },
  { key: 'people', label: 'People & Body', icon: '👋' },
  { key: 'nature', label: 'Animals & Nature', icon: '🐶' },
  { key: 'food', label: 'Food & Drink', icon: '🍕' },
  { key: 'activities', label: 'Activities', icon: '⚽' },
  { key: 'travel', label: 'Travel & Places', icon: '✈️' },
  { key: 'objects', label: 'Objects', icon: '💡' },
  { key: 'symbols', label: 'Symbols', icon: '❤️' },
  { key: 'flags', label: 'Flags', icon: '🏁' },
]

/* ─── Helpers ─── */

const ST = ['🏻', '🏼', '🏽', '🏾', '🏿']

function _e(emoji: string, names: string[], skinTones: string[] = []): EmojiEntry {
  return { emoji, names, category: 'smileys', skinTones }
}

/* ─── Raw category arrays ─── */

const SMILEYS_RAW: EmojiEntry[] = [
  _e('😀', ['grinning face', 'smile', 'happy', 'grin']),
  _e('😃', ['smiley', 'happy face', 'smile']),
  _e('😄', ['smile', 'eyes', 'happy']),
  _e('😁', ['grin', 'beaming', 'teeth']),
  _e('😆', ['laughing', 'satisfied']),
  _e('😅', ['sweat smile', 'nervous laugh']),
  _e('🤣', ['rofl', 'rolling on the floor laughing', 'lol']),
  _e('😂', ['joy', 'cry', 'tears of joy', 'laughing']),
  _e('🙂', ['slightly smiling face', 'ok']),
  _e('🙃', ['upside down face', 'silly']),
  _e('😉', ['wink', 'flirty']),
  _e('😊', ['blush', 'happy', 'shy', 'smile']),
  _e('😇', ['innocent', 'angel', 'halo']),
  _e('🥰', ['love', 'hearts', 'adore']),
  _e('😍', ['heart eyes', 'love', 'crush']),
  _e('🤩', ['star struck', 'wow', 'amazing']),
  _e('😘', ['kiss', 'love', 'face blowing a kiss']),
  _e('😗', ['kissing face', 'kiss']),
  _e('😚', ['closed eyes kiss']),
  _e('😙', ['kissing smiling']),
  _e('🥲', ['smiling tear', 'grateful', 'proud']),
  _e('😋', ['yum', 'tongue out', 'delicious']),
  _e('😛', ['stuck out tongue']),
  _e('😜', ['zany', 'tongue wink', 'crazy']),
  _e('🤪', ['crazy', 'wild', 'zany']),
  _e('😝', ['squinting tongue']),
  _e('🤑', ['money', 'rich']),
  _e('🤗', ['hug', 'hugging']),
  _e('🤭', ['oops', 'giggling']),
  _e('🤫', ['shh', 'quiet', 'shush']),
  _e('🤔', ['thinking', 'hmm', 'wondering']),
  _e('🤐', ['zipper', 'zipped mouth', 'sealed']),
  _e('🤨', ['raised eyebrow', 'skeptical', 'doubt']),
  _e('😐', ['neutral', 'meh']),
  _e('😑', ['expressionless', 'deadpan']),
  _e('😶', ['no mouth', 'silent']),
  _e('😏', ['smirk', 'flirty']),
  _e('😒', ['unamused', 'meh', 'bored']),
  _e('🙄', ['eye roll', 'annoyed']),
  _e('😬', ['grimace', 'awkward']),
  _e('🤥', ['lying', 'pinocchio']),
  _e('😌', ['relieved', 'calm', 'pensive']),
  _e('😔', ['pensive', 'sad', 'down']),
  _e('😪', ['sleepy', 'tired']),
  _e('🤤', ['drooling', 'yummy']),
  _e('😴', ['sleeping', 'zzz']),
  _e('😷', ['mask', 'sick', 'covid']),
  _e('🤒', ['thermometer', 'fever', 'sick']),
  _e('🤕', ['bandage', 'hurt']),
  _e('🤢', ['nauseated', 'sick', 'green']),
  _e('🤮', ['vomit', 'puke', 'sick']),
  _e('🥵', ['hot face', 'sweating', 'overheated']),
  _e('🥶', ['cold face', 'freezing', 'ice']),
  _e('🥴', ['woozy', 'dizzy', 'drunk']),
  _e('😵', ['dizzy', 'confused']),
  _e('🤯', ['mind blown', 'shocked', 'amazed']),
  _e('🤠', ['cowboy', 'hat']),
  _e('🥳', ['party', 'celebration', 'tada']),
  _e('🥸', ['disguise', 'glasses', 'mustache']),
  _e('😎', ['cool', 'sunglasses', 'awesome']),
  _e('🤓', ['nerd', 'geek', 'glasses']),
  _e('🧐', ['monocle', 'thinking']),
  _e('😕', ['confused', 'worried']),
  _e('😟', ['worried', 'sad']),
  _e('🙁', ['slightly frown']),
  _e('😮', ['open mouth', 'surprised']),
  _e('😯', ['hushed', 'surprised']),
  _e('😲', ['astonished', 'shocked']),
  _e('😳', ['flushed', 'embarrassed', 'blushing']),
  _e('🥺', ['pleading', 'puppy eyes', 'please']),
  _e('😦', ['anguished']),
  _e('😧', ['distressed']),
  _e('😨', ['fearful', 'scared', 'afraid']),
  _e('😰', ['anxious sweat', 'worried']),
  _e('😥', ['sad but relieved']),
  _e('😢', ['cry', 'crying', 'sad', 'tear']),
  _e('😭', ['sob', 'loudly crying', 'bawling']),
  _e('😱', ['scream', 'horror', 'terrified']),
  _e('😖', ['confounded']),
  _e('😣', ['persevere']),
  _e('😞', ['disappointed', 'down']),
  _e('😓', ['downcast sweat']),
  _e('😩', ['weary', 'tired', 'exhausted']),
  _e('😫', ['tired', 'exhausted']),
  _e('🥱', ['yawn', 'bored']),
  _e('😤', ['triumph', 'angry', 'frustrated']),
  _e('😡', ['angry', 'mad', 'rage', 'pout']),
  _e('😠', ['angry', 'mad']),
  _e('🤬', ['swearing', 'cursing']),
  _e('😈', ['devil', 'evil', 'horns']),
  _e('👿', ['angry devil']),
  _e('💀', ['skull', 'dead', 'death']),
  _e('💩', ['poop', 'poo']),
  _e('🤡', ['clown', 'funny']),
  _e('👹', ['ogre', 'monster']),
  _e('👺', ['goblin']),
  _e('👻', ['ghost', 'halloween', 'spooky']),
  _e('👽', ['alien', 'ufo', 'extraterrestrial']),
  _e('👾', ['alien monster', 'space invader']),
  _e('🤖', ['robot', 'bot', 'machine']),
  _e('😺', ['smiling cat']),
  _e('😸', ['grinning cat']),
  _e('😹', ['joy cat']),
  _e('😻', ['heart eyes cat']),
  _e('😼', ['smirk cat']),
  _e('😽', ['kissing cat']),
  _e('🙀', ['weary cat']),
  _e('😿', ['crying cat']),
  _e('😾', ['pouting cat']),
  _e('🙈', ['see no evil', 'monkey']),
  _e('🙉', ['hear no evil', 'monkey']),
  _e('🙊', ['speak no evil', 'monkey']),
  // Hands & Hearts
  _e('💌', ['love letter', 'email']),
  _e('💘', ['heart with arrow', 'cupid']),
  _e('💝', ['heart with ribbon', 'gift']),
  _e('💖', ['sparkling heart']),
  _e('💗', ['growing heart']),
  _e('💓', ['beating heart', 'heartbeat']),
  _e('💞', ['revolving hearts']),
  _e('💕', ['two hearts']),
  _e('💟', ['heart decoration']),
  _e('❣️', ['heart exclamation']),
  _e('💔', ['broken heart', 'heartbreak']),
  _e('❤️‍🔥', ['heart on fire']),
  _e('❤️‍🩹', ['mending heart']),
  _e('🫶', ['heart hands'], ST),
  _e('👐', ['open hands'], ST),
  _e('🤲', ['palms up together'], ST),
  _e('🤝', ['handshake', 'deal', 'agreement']),
  _e('🙏', ['pray', 'please', 'thank you'], ST),
]

const PEOPLE_RAW: EmojiEntry[] = [
  _e('👋', ['wave', 'hello', 'bye', 'hi'], ST),
  _e('🤚', ['raised back of hand'], ST),
  _e('🖐️', ['hand', 'fingers', 'raised hand'], ST),
  _e('✋', ['stop', 'high five', 'raised hand'], ST),
  _e('🖖', ['vulcan salute', 'spock'], ST),
  _e('🫱', ['rightwards hand'], ST),
  _e('🫲', ['leftwards hand'], ST),
  _e('🫳', ['palm down hand'], ST),
  _e('🫴', ['palm up hand'], ST),
  _e('🫷', ['leftwards pushing hand'], ST),
  _e('🫸', ['rightwards pushing hand'], ST),
  _e('👌', ['ok', 'perfect', 'okay'], ST),
  _e('🤌', ['italian hand', 'pinched fingers'], ST),
  _e('🤏', ['pinching', 'small', 'tiny'], ST),
  _e('✌️', ['peace', 'victory', 'two fingers'], ST),
  _e('🤞', ['crossed fingers', 'good luck'], ST),
  _e('🫰', ['pinched fingers'], ST),
  _e('🤟', ['love you', 'rock on'], ST),
  _e('🤘', ['rock on', 'horns'], ST),
  _e('🤙', ['call me', 'shaka'], ST),
  _e('👈', ['point left', 'left'], ST),
  _e('👉', ['point right', 'right'], ST),
  _e('👆', ['point up', 'up'], ST),
  _e('🖕', ['middle finger'], ST),
  _e('👇', ['point down', 'down'], ST),
  _e('☝️', ['index up', 'pointing up'], ST),
  _e('🫵', ['pointing at you'], ST),
  _e('👍', ['thumbs up', 'like', 'approve', 'yes'], ST),
  _e('👎', ['thumbs down', 'dislike', 'no'], ST),
  _e('✊', ['fist', 'punch', 'power'], ST),
  _e('👊', ['fist bump', 'punch', 'brofist'], ST),
  _e('🤛', ['left fist bump'], ST),
  _e('🤜', ['right fist bump'], ST),
  _e('👏', ['clap', 'applause', 'bravo'], ST),
  _e('🙌', ['raised hands', 'hooray', 'celebrate'], ST),
  _e('🫶', ['heart hands'], ST),
  _e('👐', ['open hands'], ST),
  _e('🤲', ['palms up together'], ST),
  _e('🤝', ['handshake', 'deal', 'agreement']),
  _e('🙏', ['pray', 'please', 'thank you', 'hope', 'namaste'], ST),
  _e('💪', ['strong', 'muscle', 'bicep', 'flex', 'workout', 'gym'], ST),
  _e('🦾', ['mechanical arm']),
  _e('🦿', ['mechanical leg']),
  _e('🦵', ['leg', 'kick'], ST),
  _e('🦶', ['foot', 'kick'], ST),
  _e('👂', ['ear', 'hear', 'listen'], ST),
  _e('🦻', ['ear with hearing aid'], ST),
  _e('👃', ['nose', 'smell'], ST),
  _e('🧠', ['brain', 'smart', 'intelligent']),
  _e('🫀', ['anatomical heart']),
  _e('🫁', ['lungs']),
  _e('🦷', ['tooth', 'dentist']),
  _e('🦴', ['bone', 'skeleton']),
  _e('👀', ['eyes', 'look', 'watching', 'staring']),
  _e('👁️', ['eye']),
  _e('👅', ['tongue']),
  _e('👄', ['mouth', 'lips']),
  _e('👶', ['baby', 'infant'], ST),
  _e('🧒', ['child', 'kid'], ST),
  _e('👦', ['boy'], ST),
  _e('👧', ['girl'], ST),
  _e('🧑', ['person', 'adult'], ST),
  _e('👱', ['blond person'], ST),
  _e('👨', ['man', 'male'], ST),
  _e('🧔', ['person with beard'], ST),
  _e('👩', ['woman', 'female'], ST),
  _e('🧓', ['older person', 'elderly'], ST),
  _e('👴', ['old man', 'elderly'], ST),
  _e('👵', ['old woman', 'elderly'], ST),
  _e('🙍', ['frowning person'], ST),
  _e('🙎', ['pouting person'], ST),
  _e('🙅', ['no good', 'ng'], ST),
  _e('🙆', ['ok person'], ST),
  _e('💁', ['information desk'], ST),
  _e('🙋', ['raising hand'], ST),
  _e('🧏', ['deaf person'], ST),
  _e('🙇', ['bowing', 'apology'], ST),
  _e('🤦', ['facepalm', 'doh'], ST),
  _e('🤷', ['shrug', 'idk', 'dunno'], ST),
  // Gestures
  _e('👋', ['wave', 'hello', 'bye', 'hi'], ST),
  _e('🤚', ['raised back of hand'], ST),
  _e('🖐️', ['hand', 'fingers', 'raised hand'], ST),
  _e('✋', ['stop', 'high five', 'raised hand'], ST),
  _e('🖖', ['vulcan salute', 'spock'], ST),
  _e('🫱', ['rightwards hand'], ST),
  _e('🫲', ['leftwards hand'], ST),
  _e('🫳', ['palm down hand'], ST),
  _e('🫴', ['palm up hand'], ST),
  _e('🫷', ['leftwards pushing hand'], ST),
  _e('🫸', ['rightwards pushing hand'], ST),
  _e('👌', ['ok', 'perfect', 'okay'], ST),
  _e('🤌', ['italian hand', 'pinched fingers'], ST),
  _e('🤏', ['pinching', 'small', 'tiny'], ST),
  _e('✌️', ['peace', 'victory', 'two fingers'], ST),
  _e('🤞', ['crossed fingers', 'good luck'], ST),
  _e('🫰', ['pinched fingers'], ST),
  _e('🤟', ['love you', 'rock on'], ST),
  _e('🤘', ['rock on', 'horns'], ST),
  _e('🤙', ['call me', 'shaka'], ST),
  _e('👈', ['point left', 'left'], ST),
  _e('👉', ['point right', 'right'], ST),
  _e('👆', ['point up', 'up'], ST),
  _e('🖕', ['middle finger'], ST),
  _e('👇', ['point down', 'down'], ST),
  _e('☝️', ['index up', 'pointing up'], ST),
  _e('🫵', ['pointing at you'], ST),
  _e('👍', ['thumbs up', 'like', 'approve', 'yes'], ST),
  _e('👎', ['thumbs down', 'dislike', 'no'], ST),
  _e('✊', ['fist', 'punch', 'power'], ST),
  _e('👊', ['fist bump', 'punch', 'brofist'], ST),
  _e('🤛', ['left fist bump'], ST),
  _e('🤜', ['right fist bump'], ST),
  _e('👏', ['clap', 'applause', 'bravo'], ST),
  _e('🙌', ['raised hands', 'hooray', 'celebrate'], ST),
  _e('🫶', ['heart hands'], ST),
  _e('👐', ['open hands'], ST),
  _e('🤲', ['palms up together'], ST),
  _e('🤝', ['handshake', 'deal', 'agreement']),
  _e('🙏', ['pray', 'please', 'thank you', 'hope', 'namaste'], ST),
  _e('💪', ['strong', 'muscle', 'bicep', 'flex', 'workout', 'gym'], ST),
  _e('🦾', ['mechanical arm']),
  _e('🦿', ['mechanical leg']),
  _e('🦵', ['leg', 'kick'], ST),
  _e('🦶', ['foot', 'kick'], ST),
  _e('👂', ['ear', 'hear', 'listen'], ST),
  _e('🦻', ['ear with hearing aid'], ST),
  _e('👃', ['nose', 'smell'], ST),
  _e('🧠', ['brain', 'smart', 'intelligent']),
  _e('🫀', ['anatomical heart']),
  _e('🫁', ['lungs']),
  _e('🦷', ['tooth', 'dentist']),
  _e('🦴', ['bone', 'skeleton']),
  _e('👀', ['eyes', 'look', 'watching', 'staring']),
  _e('👁️', ['eye']),
  _e('👅', ['tongue']),
  _e('👄', ['mouth', 'lips']),
  // People
  _e('👶', ['baby', 'infant'], ST),
  _e('🧒', ['child', 'kid'], ST),
  _e('👦', ['boy'], ST),
  _e('👧', ['girl'], ST),
  _e('🧑', ['person', 'adult'], ST),
  _e('👱', ['blond person'], ST),
  _e('👨', ['man', 'male'], ST),
  _e('🧔', ['person with beard'], ST),
  _e('👩', ['woman', 'female'], ST),
  _e('🧓', ['older person', 'elderly'], ST),
  _e('👴', ['old man', 'elderly'], ST),
  _e('👵', ['old woman', 'elderly'], ST),
  _e('🙍', ['frowning person'], ST),
  _e('🙎', ['pouting person'], ST),
  _e('🙅', ['no good', 'ng'], ST),
  _e('🙆', ['ok person'], ST),
  _e('💁', ['information desk'], ST),
  _e('🙋', ['raising hand'], ST),
  _e('🧏', ['deaf person'], ST),
  _e('🙇', ['bowing', 'apology'], ST),
  _e('🤦', ['facepalm', 'doh'], ST),
  _e('🤷', ['shrug', 'idk', 'dunno'], ST),
  _e('🧑‍⚕️', ['health worker'], ST),
  _e('🧑‍🎓', ['student'], ST),
  _e('🧑‍🏫', ['teacher'], ST),
  _e('🧑‍⚖️', ['judge'], ST),
  _e('🧑‍🌾', ['farmer'], ST),
  _e('🧑‍🍳', ['cook', 'chef'], ST),
  _e('🧑‍🔧', ['mechanic'], ST),
  _e('🧑‍🏭', ['factory worker'], ST),
  _e('🧑‍💻', ['technologist', 'programmer'], ST),
  _e('🧑‍🔬', ['scientist'], ST),
  _e('🧑‍🚀', ['astronaut'], ST),
  _e('🧑‍🚒', ['firefighter'], ST),
  _e('👮', ['police officer', 'cop'], ST),
  _e('🕵️', ['detective', 'spy'], ST),
  _e('💂', ['guard', 'guardsman'], ST),
  _e('🥷', ['ninja'], ST),
  _e('👷', ['construction worker'], ST),
  _e('🫅', ['person with crown'], ST),
  _e('🤴', ['prince'], ST),
  _e('👸', ['princess'], ST),
  _e('👳', ['person with turban'], ST),
  _e('👲', ['person with skullcap'], ST),
  _e('🧕', ['woman with headscarf'], ST),
  _e('🤵', ['person in tuxedo'], ST),
  _e('👰', ['person with veil'], ST),
  _e('🤰', ['pregnant woman'], ST),
  _e('🫃', ['pregnant man']),
  _e('🫄', ['pregnant person']),
  _e('🤱', ['breastfeeding'], ST),
  _e('👼', ['baby angel', 'cherub'], ST),
  _e('🎅', ['santa claus', 'santa', 'christmas'], ST),
  _e('🤶', ['mrs claus', 'christmas'], ST),
  _e('🦸', ['superhero'], ST),
  _e('🦹', ['supervillain'], ST),
  _e('🧙', ['mage', 'wizard'], ST),
  _e('🧚', ['fairy'], ST),
  _e('🧛', ['vampire'], ST),
  _e('🧜', ['merperson'], ST),
  _e('🧝', ['elf'], ST),
  _e('🧞', ['genie']),
  _e('🧟', ['zombie']),
  _e('🧌', ['troll']),
  _e('💃', ['woman dancing', 'dance'], ST),
  _e('🕺', ['man dancing', 'dance'], ST),
  _e('👯', ['people with bunny ears'], ST),
  _e('🧖', ['person in steamy room'], ST),
  _e('👫', ['woman and man holding hands'], ST),
  _e('👬', ['men holding hands'], ST),
  _e('👭', ['women holding hands'], ST),
  _e('💏', ['kiss'], ST),
  _e('💑', ['couple with heart'], ST),
  _e('👨‍👩‍👦', ['family man woman boy']),
  _e('👨‍👩‍👧', ['family man woman girl']),
  _e('👨‍👩‍👧‍👦', ['family man woman girl boy']),
  _e('👨‍👩‍👦‍👦', ['family man woman boy boy']),
  _e('👨‍👩‍👧‍👧', ['family man woman girl girl']),
  _e('👨‍👦', ['family man boy']),
  _e('👨‍👧', ['family man girl']),
  _e('👩‍👦', ['family woman boy']),
  _e('👩‍👧', ['family woman girl']),
]

const NATURE_RAW: EmojiEntry[] = [
  _e('🐶', ['dog', 'puppy', 'pup', 'doggo']),
  _e('🐱', ['cat', 'kitty', 'kitten']),
  _e('🐭', ['mouse']),
  _e('🐹', ['hamster']),
  _e('🐰', ['rabbit', 'bunny']),
  _e('🦊', ['fox']),
  _e('🐻', ['bear']),
  _e('🐼', ['panda']),
  _e('🐨', ['koala']),
  _e('🐯', ['tiger']),
  _e('🦁', ['lion']),
  _e('🐮', ['cow', 'ox']),
  _e('🐷', ['pig']),
  _e('🐽', ['pig nose']),
  _e('🐸', ['frog']),
  _e('🐵', ['monkey']),
  _e('🐒', ['monkey face']),
  _e('🙈', ['see no evil monkey']),
  _e('🙉', ['hear no evil monkey']),
  _e('🙊', ['speak no evil monkey']),
  _e('🐔', ['chicken', 'hen']),
  _e('🐧', ['penguin']),
  _e('🐦', ['bird']),
  _e('🐤', ['baby chick']),
  _e('🐣', ['hatching chick']),
  _e('🐥', ['front facing baby chick']),
  _e('🦆', ['duck']),
  _e('🦅', ['eagle']),
  _e('🦉', ['owl']),
  _e('🦇', ['bat']),
  _e('🐺', ['wolf']),
  _e('🐗', ['boar']),
  _e('🐴', ['horse', 'gallop']),
  _e('🦄', ['unicorn']),
  _e('🐝', ['bee', 'honeybee']),
  _e('🪱', ['worm']),
  _e('🐛', ['bug', 'caterpillar']),
  _e('🦋', ['butterfly']),
  _e('🐌', ['snail']),
  _e('🐞', ['ladybug']),
  _e('🐜', ['ant']),
  _e('🪰', ['fly']),
  _e('🪲', ['beetle']),
  _e('🪳', ['cockroach']),
  _e('🦟', ['mosquito']),
  _e('🦗', ['cricket']),
  _e('🕷️', ['spider']),
  _e('🕸️', ['spider web']),
  _e('🦂', ['scorpion']),
  _e('🐢', ['turtle', 'tortoise']),
  _e('🐍', ['snake']),
  _e('🦎', ['lizard']),
  _e('🦖', ['t-rex', 'trex']),
  _e('🦕', ['sauropod']),
  _e('🐙', ['octopus']),
  _e('🦑', ['squid']),
  _e('🦐', ['shrimp']),
  _e('🦞', ['lobster']),
  _e('🦀', ['crab']),
  _e('🪼', ['jellyfish']),
  _e('🪸', ['coral']),
  _e('🐠', ['tropical fish']),
  _e('🐟', ['fish']),
  _e('🐡', ['blowfish']),
  _e('🐬', ['dolphin']),
  _e('🐳', ['whale']),
  _e('🐋', ['whale spout']),
  _e('🦈', ['shark']),
  _e('🐊', ['crocodile', 'alligator']),
  _e('🦓', ['zebra']),
  _e('🦍', ['gorilla']),
  _e('🦧', ['orangutan']),
  _e('🐘', ['elephant']),
  _e('🦣', ['mammoth']),
  _e('🦛', ['hippo']),
  _e('🦏', ['rhinoceros']),
  _e('🐪', ['camel']),
  _e('🐫', ['two hump camel']),
  _e('🦒', ['giraffe']),
  _e('🦘', ['kangaroo']),
  _e('🦬', ['bison']),
  _e('🐃', ['water buffalo']),
  _e('🐂', ['ox']),
  _e('🐄', ['cow']),
  _e('🐑', ['sheep', 'ewe']),
  _e('🦙', ['llama']),
  _e('🐐', ['goat']),
  _e('🦌', ['deer']),
  _e('🐕', ['dog']),
  _e('🐩', ['poodle']),
  _e('🦮', ['guide dog']),
  _e('🐕‍🦺', ['service dog']),
  _e('🐈', ['cat']),
  _e('🐈‍⬛', ['black cat']),
  _e('🪶', ['feather']),
  _e('🐓', ['rooster']),
  _e('🦃', ['turkey']),
  _e('🦤', ['dodo']),
  _e('🦚', ['peacock']),
  _e('🦜', ['parrot']),
  _e('🪽', ['wing']),
  _e('🪶', ['feather']),
  _e('🦢', ['swan']),
  _e('🦩', ['flamingo']),
  _e('🕊️', ['dove', 'peace']),
  _e('🦝', ['raccoon']),
  _e('🦨', ['skunk']),
  _e('🦘', ['kangaroo']),
  _e('🦡', ['badger']),
  _e('🦦', ['otter']),
  _e('🦥', ['sloth']),
  _e('🦔', ['hedgehog']),
  _e('🐾', ['paw prints']),
  // Plants
  _e('🌸', ['cherry blossom', 'sakura']),
  _e('💮', ['white flower']),
  _e('🪷', ['lotus']),
  _e('🏵️', ['rosette']),
  _e('🌹', ['rose', 'flower', 'red rose']),
  _e('🥀', ['wilted flower']),
  _e('🌺', ['hibiscus', 'flower']),
  _e('🌻', ['sunflower']),
  _e('🌼', ['blossom', 'flower']),
  _e('🌷', ['tulip']),
  _e('🪷', ['lotus']),
  _e('🌱', ['seedling', 'sprout', 'plant', 'grow']),
  _e('🪴', ['potted plant']),
  _e('🌲', ['evergreen tree']),
  _e('🌳', ['deciduous tree']),
  _e('🌴', ['palm tree']),
  _e('🌵', ['cactus']),
  _e('🌾', ['sheaf of rice', 'harvest']),
  _e('🌿', ['herb', 'green', 'leaf']),
  _e('☘️', ['shamrock', 'clover']),
  _e('🍀', ['four leaf clover', 'lucky']),
  _e('🍁', ['maple leaf', 'fall', 'canada']),
  _e('🍂', ['fallen leaf', 'autumn']),
  _e('🍃', ['leaf fluttering', 'blow']),
  _e('🪹', ['empty nest']),
  _e('🪺', ['nest with eggs']),
  _e('🍄', ['mushroom']),
  _e('🪨', ['rock']),
  _e('🪵', ['wood']),
  _e('🌰', ['chestnut']),
  // Weather / Sky
  _e('🌍', ['earth africa', 'world', 'earth']),
  _e('🌎', ['earth americas', 'world']),
  _e('🌏', ['earth asia', 'world']),
  _e('☀️', ['sun', 'sunny', 'bright']),
  _e('🌤️', ['sun behind small cloud']),
  _e('⛅', ['partly cloudy']),
  _e('🌥️', ['sun behind large cloud']),
  _e('☁️', ['cloud', 'cloudy']),
  _e('🌦️', ['sun behind rain cloud']),
  _e('🌧️', ['cloud with rain']),
  _e('⛈️', ['storm', 'cloud with lightning and rain']),
  _e('🌩️', ['thunder', 'cloud with lightning']),
  _e('🌪️', ['tornado']),
  _e('🌫️', ['fog']),
  _e('🌬️', ['wind face', 'windy']),
  _e('🌀', ['cyclone', 'hurricane']),
  _e('🌈', ['rainbow']),
  _e('🌂', ['closed umbrella']),
  _e('☂️', ['umbrella']),
  _e('☔', ['umbrella with rain']),
  _e('⛱️', ['umbrella on ground']),
  _e('⚡', ['lightning', 'bolt', 'thunder', 'electric']),
  _e('❄️', ['snowflake', 'cold', 'winter']),
  _e('☃️', ['snowman']),
  _e('⛄', ['snowman without snow']),
  _e('☄️', ['comet']),
  _e('🔥', ['fire', 'hot', 'lit', 'flame', 'burning', 'trending']),
  _e('💧', ['droplet', 'water', 'sweat']),
  _e('🌊', ['wave', 'ocean', 'water', 'surf']),
  _e('🎃', ['jack o lantern', 'halloween']),
  _e('🎄', ['christmas tree']),
  _e('🎆', ['fireworks']),
  _e('🎇', ['sparkler']),
  _e('✨', ['sparkles', 'sparkle', 'shine', 'glitter']),
  _e('💫', ['dizzy', 'star']),
  _e('⭐', ['star']),
  _e('🌟', ['glowing star', 'sparkle']),
  _e('🌙', ['moon', 'crescent moon', 'night']),
  _e('🌛', ['first quarter moon face']),
  _e('🌜', ['last quarter moon face']),
  _e('🌚', ['new moon face']),
  _e('🌞', ['sun with face']),
]

const FOOD_RAW: EmojiEntry[] = [
  _e('🍇', ['grapes']),
  _e('🍈', ['melon']),
  _e('🍉', ['watermelon']),
  _e('🍊', ['tangerine', 'orange']),
  _e('🍋', ['lemon']),
  _e('🍌', ['banana']),
  _e('🍍', ['pineapple']),
  _e('🥭', ['mango']),
  _e('🍎', ['red apple']),
  _e('🍏', ['green apple']),
  _e('🍐', ['pear']),
  _e('🍑', ['peach']),
  _e('🍒', ['cherries']),
  _e('🍓', ['strawberry']),
  _e('🫐', ['blueberries']),
  _e('🥝', ['kiwi']),
  _e('🍅', ['tomato']),
  _e('🫒', ['olive']),
  _e('🥥', ['coconut']),
  _e('🥑', ['avocado']),
  _e('🍆', ['eggplant', 'aubergine']),
  _e('🥔', ['potato']),
  _e('🥕', ['carrot']),
  _e('🌽', ['ear of corn']),
  _e('🌶️', ['hot pepper']),
  _e('🫑', ['bell pepper']),
  _e('🥒', ['cucumber']),
  _e('🥬', ['leafy green']),
  _e('🥦', ['broccoli']),
  _e('🧄', ['garlic']),
  _e('🧅', ['onion']),
  _e('🥜', ['peanuts']),
  _e('🫘', ['beans']),
  _e('🌰', ['chestnut']),
  _e('🫚', ['ginger root']),
  _e('🫛', ['pea pod']),
  _e('🍞', ['bread']),
  _e('🥐', ['croissant']),
  _e('🥖', ['baguette']),
  _e('🫓', ['flatbread']),
  _e('🥨', ['pretzel']),
  _e('🥯', ['bagel']),
  _e('🥞', ['pancakes']),
  _e('🧇', ['waffle']),
  _e('🧀', ['cheese', 'cheese wedge']),
  _e('🍖', ['meat on bone']),
  _e('🍗', ['poultry leg', 'drumstick']),
  _e('🥩', ['steak', 'meat']),
  _e('🥓', ['bacon']),
  _e('🍔', ['hamburger', 'burger']),
  _e('🍟', ['french fries', 'fries']),
  _e('🍕', ['pizza']),
  _e('🌭', ['hot dog']),
  _e('🥪', ['sandwich']),
  _e('🌮', ['taco']),
  _e('🌯', ['burrito']),
  _e('🫔', ['tamale']),
  _e('🥙', ['stuffed flatbread']),
  _e('🧆', ['falafel']),
  _e('🥚', ['egg']),
  _e('🍳', ['fried egg', 'cooking', 'breakfast']),
  _e('🥘', ['shallow pan of food']),
  _e('🍲', ['pot of food', 'stew']),
  _e('🫕', ['fondue']),
  _e('🥣', ['bowl with spoon']),
  _e('🥗', ['green salad', 'salad']),
  _e('🍿', ['popcorn']),
  _e('🧈', ['butter']),
  _e('🧂', ['salt']),
  _e('🥫', ['canned food']),
  _e('🍱', ['bento box']),
  _e('🍘', ['rice cracker']),
  _e('🍙', ['rice ball']),
  _e('🍚', ['cooked rice']),
  _e('🍛', ['curry']),
  _e('🍜', ['steaming bowl', 'ramen', 'noodles']),
  _e('🍝', ['spaghetti', 'pasta']),
  _e('🍠', ['roasted sweet potato']),
  _e('🍢', ['oden']),
  _e('🍣', ['sushi']),
  _e('🍤', ['fried shrimp', 'tempura']),
  _e('🍥', ['fish cake']),
  _e('🥮', ['moon cake']),
  _e('🍡', ['dango']),
  _e('🥟', ['dumpling', 'gyoza']),
  _e('🥠', ['fortune cookie']),
  _e('🥡', ['takeout box']),
  _e('🦀', ['crab']),
  _e('🦞', ['lobster']),
  _e('🦐', ['shrimp']),
  _e('🦑', ['squid']),
  _e('🍦', ['soft ice cream', 'ice cream']),
  _e('🍧', ['shaved ice']),
  _e('🍨', ['ice cream']),
  _e('🍩', ['doughnut', 'donut']),
  _e('🍪', ['cookie', 'biscuit']),
  _e('🎂', ['birthday cake', 'celebration']),
  _e('🍰', ['shortcake']),
  _e('🧁', ['cupcake']),
  _e('🥧', ['pie']),
  _e('🍫', ['chocolate bar', 'chocolate']),
  _e('🍬', ['candy', 'sweets']),
  _e('🍭', ['lollipop']),
  _e('🍮', ['custard', 'pudding']),
  _e('🍯', ['honey']),
  _e('🍼', ['baby bottle', 'milk']),
  _e('🥛', ['glass of milk']),
  _e('☕', ['coffee', 'cup', 'mug', 'tea']),
  _e('🫖', ['teapot']),
  _e('🍵', ['teacup', 'matcha', 'green tea']),
  _e('🍶', ['sake']),
  _e('🍾', ['champagne']),
  _e('🍷', ['wine glass', 'wine']),
  _e('🍸', ['cocktail', 'martini', 'drink']),
  _e('🍹', ['tropical drink', 'tiki']),
  _e('🍺', ['beer', 'drinking']),
  _e('🍻', ['beers', 'cheers', 'clinking beers']),
  _e('🥂', ['clinking glasses', 'celebration', 'toast']),
  _e('🥃', ['tumbler glass', 'whiskey', 'bourbon']),
  _e('🫗', ['pouring liquid']),
  _e('🥤', ['cup with straw', 'soda', 'drink']),
  _e('🧋', ['bubble tea', 'boba']),
  _e('🧃', ['juice box']),
  _e('🧉', ['mate']),
  _e('🧊', ['ice']),
  _e('🥢', ['chopsticks']),
  _e('🍽️', ['plate with fork and knife']),
  _e('🍴', ['fork and knife']),
  _e('🥄', ['spoon']),
  _e('🔪', ['kitchen knife', 'knife']),
]

const ACTIVITIES_RAW: EmojiEntry[] = [
  _e('⚽', ['soccer', 'football', 'ball']),
  _e('⚾', ['baseball']),
  _e('🥎', ['softball']),
  _e('🏀', ['basketball', 'ball']),
  _e('🏐', ['volleyball']),
  _e('🏈', ['american football', 'football']),
  _e('🏉', ['rugby']),
  _e('🎾', ['tennis', 'ball']),
  _e('🥏', ['flying disc']),
  _e('🎳', ['bowling']),
  _e('🏏', ['cricket game']),
  _e('🏑', ['field hockey']),
  _e('🏒', ['ice hockey']),
  _e('🥍', ['lacrosse']),
  _e('🏓', ['ping pong', 'table tennis']),
  _e('🏸', ['badminton']),
  _e('🥊', ['boxing glove']),
  _e('🥋', ['martial arts', 'karate', 'judo']),
  _e('🥅', ['goal net']),
  _e('⛳', ['golf', 'flag in hole']),
  _e('⛸️', ['ice skate']),
  _e('🎣', ['fishing', 'fish']),
  _e('🤿', ['diving mask']),
  _e('🎽', ['running shirt']),
  _e('🎿', ['skis', 'skiing']),
  _e('🛷', ['sled']),
  _e('🥌', ['curling stone']),
  _e('🎯', ['bullseye', 'target', 'direct hit']),
  _e('🪀', ['yo-yo']),
  _e('🪁', ['kite']),
  _e('🔫', ['water pistol']),
  _e('🎱', ['billiards', '8 ball', 'pool']),
  _e('🔮', ['crystal ball', 'magic', 'future']),
  _e('🪄', ['magic wand']),
  _e('🎮', ['video game', 'controller', 'gaming']),
  _e('🕹️', ['joystick']),
  _e('🎰', ['slot machine', 'casino', 'jackpot']),
  _e('🎲', ['dice', 'game']),
  _e('🧩', ['puzzle piece', 'jigsaw', 'puzzle']),
  _e('🧸', ['teddy bear']),
  _e('🪅', ['pinata']),
  _e('🪩', ['mirror ball']),
  _e('🪆', ['nesting dolls']),
  _e('♠️', ['spade suit']),
  _e('♥️', ['heart suit']),
  _e('♦️', ['diamond suit']),
  _e('♣️', ['club suit']),
  _e('♟️', ['chess pawn']),
  _e('🃏', ['joker']),
  _e('🀄', ['mahjong red dragon']),
  _e('🎴', ['flower playing cards']),
  _e('🎭', ['performing arts', 'theater', 'masks']),
  _e('🎨', ['art', 'palette', 'paint', 'creative', 'design']),
  _e('🧵', ['thread', 'sewing']),
  _e('🧶', ['yarn', 'knitting']),
  _e('🪡', ['sewing needle']),
  _e('🎼', ['musical score', 'music']),
  _e('🎵', ['musical note']),
  _e('🎶', ['musical notes']),
  _e('🎙️', ['studio microphone']),
  _e('🎚️', ['level slider']),
  _e('🎛️', ['control knobs']),
  _e('🎤', ['microphone', 'mic', 'karaoke', 'sing']),
  _e('🎧', ['headphones', 'headset', 'music']),
  _e('📻', ['radio']),
  _e('🎷', ['saxophone']),
  _e('🪗', ['accordion']),
  _e('🎸', ['guitar', 'rock', 'band']),
  _e('🎹', ['piano', 'musical keyboard']),
  _e('🎺', ['trumpet']),
  _e('🎻', ['violin']),
  _e('🪕', ['banjo']),
  _e('🥁', ['drum', 'drumstick']),
  _e('🪘', ['long drum']),
  _e('🪇', ['maracas']),
  _e('🪈', ['flute']),
  _e('🎬', ['clapper board', 'movie', 'film']),
  _e('🎪', ['circus tent']),
]

const TRAVEL_RAW: EmojiEntry[] = [
  _e('🚗', ['car', 'automobile', 'red car']),
  _e('🚕', ['taxi', 'cab']),
  _e('🚙', ['blue car']),
  _e('🚌', ['bus']),
  _e('🏎️', ['racing car', 'race car']),
  _e('🚓', ['police car']),
  _e('🚑', ['ambulance']),
  _e('🚒', ['fire engine', 'fire truck']),
  _e('🚐', ['minibus', 'van']),
  _e('🛻', ['pickup truck']),
  _e('🚚', ['delivery truck', 'lorry']),
  _e('🚛', ['articulated lorry', 'semi truck']),
  _e('🚜', ['tractor']),
  _e('🏍️', ['motorcycle', 'racing']),
  _e('🛵', ['motor scooter', 'scooter']),
  _e('🦽', ['manual wheelchair']),
  _e('🦼', ['motorized wheelchair']),
  _e('🛺', ['auto rickshaw']),
  _e('🚲', ['bicycle', 'bike']),
  _e('🛴', ['kick scooter']),
  _e('🛹', ['skateboard']),
  _e('🛼', ['roller skate']),
  _e('🚏', ['bus stop']),
  _e('🛣️', ['motorway', 'highway', 'road']),
  _e('🛤️', ['railway track']),
  _e('🛢️', ['oil drum']),
  _e('⛽', ['fuel pump', 'gas station']),
  _e('🛞', ['wheel']),
  _e('🚨', ['police car light', 'siren']),
  _e('🚥', ['horizontal traffic light']),
  _e('🚦', ['vertical traffic light']),
  _e('🛑', ['stop sign']),
  _e('🚧', ['construction']),
  _e('⚓', ['anchor']),
  _e('🛟', ['ring buoy']),
  _e('⛵', ['sailboat', 'sailing']),
  _e('🛶', ['canoe']),
  _e('🚤', ['speedboat', 'motor boat']),
  _e('🛳️', ['passenger ship', 'cruise ship']),
  _e('⛴️', ['ferry']),
  _e('🚢', ['ship', 'boat', 'cruise']),
  _e('✈️', ['airplane', 'flight', 'fly', 'plane', 'travel']),
  _e('🛩️', ['small airplane', 'airliner']),
  _e('🛫', ['airplane departure', 'takeoff']),
  _e('🛬', ['airplane arrival', 'landing']),
  _e('🪂', ['parachute']),
  _e('💺', ['seat']),
  _e('🚁', ['helicopter']),
  _e('🚟', ['suspension railway']),
  _e('🚠', ['mountain cableway']),
  _e('🚡', ['aerial tramway']),
  _e('🛰️', ['satellite']),
  _e('🚀', ['rocket', 'space', 'launch', 'nasa']),
  _e('🛸', ['flying saucer', 'ufo']),
  _e('🛎️', ['bellhop bell']),
  _e('🧳', ['luggage']),
  _e('⌛', ['hourglass done']),
  _e('⏳', ['hourglass not done']),
  _e('⌚', ['watch', 'time']),
  _e('⏰', ['alarm clock', 'wake up', 'time']),
  _e('⏱️', ['stopwatch']),
  _e('⏲️', ['timer clock']),
  _e('🕰️', ['mantelpiece clock']),
  _e('🕛', ['twelve o clock']),
  _e('🕧', ['twelve thirty']),
  _e('🕐', ['one o clock']),
  _e('🕜', ['one thirty']),
  _e('🕑', ['two o clock']),
  _e('🕝', ['two thirty']),
  _e('🕒', ['three o clock']),
  _e('🕞', ['three thirty']),
  _e('🕓', ['four o clock']),
  _e('🕟', ['four thirty']),
  _e('🕔', ['five o clock']),
  _e('🕠', ['five thirty']),
  _e('🕕', ['six o clock']),
  _e('🕡', ['six thirty']),
  _e('🕖', ['seven o clock']),
  _e('🕢', ['seven thirty']),
  _e('🕗', ['eight o clock']),
  _e('🕣', ['eight thirty']),
  _e('🕘', ['nine o clock']),
  _e('🕤', ['nine thirty']),
  _e('🕙', ['ten o clock']),
  _e('🕥', ['ten thirty']),
  _e('🕚', ['eleven o clock']),
  _e('🕦', ['eleven thirty']),
  _e('🌑', ['new moon']),
  _e('🌒', ['waxing crescent moon']),
  _e('🌓', ['first quarter moon']),
  _e('🌔', ['waxing gibbous moon']),
  _e('🌕', ['full moon']),
  _e('🌖', ['waning gibbous moon']),
  _e('🌗', ['last quarter moon']),
  _e('🌘', ['waning crescent moon']),
  _e('🌙', ['moon', 'crescent moon', 'night']),
  _e('🌚', ['new moon face']),
  _e('🌛', ['first quarter moon face']),
  _e('🌜', ['last quarter moon face']),
  _e('🌡️', ['thermometer']),
  _e('☀️', ['sun', 'sunny', 'bright']),
  _e('🌝', ['sun with face']),
  _e('🌞', ['sun with face']),
  _e('🪐', ['ringed planet']),
  _e('⭐', ['star']),
  _e('🌟', ['glowing star']),
  _e('🌠', ['shooting star']),
  _e('🌌', ['milky way']),
  _e('☁️', ['cloud']),
  _e('⛅', ['partly cloudy']),
  _e('⛈️', ['storm']),
  _e('🌤️', ['sun behind small cloud']),
  _e('🌥️', ['sun behind large cloud']),
  _e('🌦️', ['sun behind rain cloud']),
  _e('🌧️', ['cloud with rain']),
  _e('🌨️', ['cloud with snow']),
  _e('🌩️', ['cloud with lightning']),
  _e('🌪️', ['tornado']),
  _e('🌫️', ['fog']),
  _e('🌬️', ['wind face']),
  _e('🌈', ['rainbow']),
  _e('🌂', ['closed umbrella']),
  _e('☂️', ['umbrella']),
  _e('☔', ['umbrella with rain']),
  _e('⛱️', ['umbrella on ground']),
  _e('⚡', ['lightning', 'bolt']),
  _e('❄️', ['snowflake']),
  _e('☃️', ['snowman']),
  _e('⛄', ['snowman without snow']),
  _e('☄️', ['comet']),
  _e('🔥', ['fire', 'flame']),
  _e('💧', ['droplet', 'water']),
  _e('🌊', ['wave', 'ocean']),
  _e('🎃', ['jack o lantern']),
  _e('🎄', ['christmas tree']),
  _e('🎆', ['fireworks']),
  _e('🎇', ['sparkler']),
  _e('✨', ['sparkles']),
  _e('🏠', ['house', 'home']),
  _e('🏡', ['house with garden']),
  _e('🏢', ['office building']),
  _e('🏣', ['japanese post office']),
  _e('🏤', ['post office']),
  _e('🏥', ['hospital']),
  _e('🏦', ['bank']),
  _e('🏨', ['hotel']),
  _e('🏩', ['love hotel']),
  _e('🏪', ['convenience store']),
  _e('🏫', ['school']),
  _e('🏬', ['department store']),
  _e('🏭', ['factory']),
  _e('🏯', ['japanese castle']),
  _e('🏰', ['castle', 'palace']),
  _e('💒', ['wedding', 'church']),
  _e('🗼', ['tokyo tower']),
  _e('🗽', ['statue of liberty']),
  _e('⛪', ['church']),
  _e('🕌', ['mosque']),
  _e('🛕', ['hindu temple']),
  _e('⛩️', ['shinto shrine']),
  _e('🕋', ['kaaba']),
  _e('⛲', ['fountain']),
  _e('⛺', ['tent', 'camping']),
  _e('🌁', ['foggy']),
  _e('🌃', ['night with stars', 'city night']),
  _e('🏙️', ['cityscape']),
  _e('🌄', ['sunrise over mountains']),
  _e('🌅', ['sunset', 'sunrise']),
  _e('🌆', ['city sunset']),
  _e('🌇', ['city sunrise']),
  _e('🌉', ['bridge at night']),
  _e('🎠', ['carousel horse']),
  _e('🛝', ['playground slide']),
  _e('🎡', ['ferris wheel']),
  _e('🎢', ['roller coaster']),
  _e('💈', ['barber pole']),
  _e('🎪', ['circus tent']),
  _e('🚂', ['steam locomotive']),
  _e('🚃', ['railway car']),
  _e('🚄', ['high speed train']),
  _e('🚅', ['bullet train']),
  _e('🚆', ['train']),
  _e('🚇', ['metro', 'subway']),
  _e('🚈', ['light rail']),
  _e('🚉', ['train station']),
  _e('🚊', ['tram']),
  _e('🚝', ['monorail']),
  _e('🚞', ['mountain railway']),
  _e('🚋', ['tram', 'streetcar']),
  _e('🚍', ['oncoming bus']),
  _e('🚎', ['trolleybus']),
  _e('🚐', ['minibus']),
  _e('🚑', ['ambulance']),
  _e('🚒', ['fire engine']),
  _e('🚓', ['police car']),
  _e('🚔', ['oncoming police car']),
  _e('🚕', ['taxi']),
  _e('🚖', ['oncoming taxi']),
  _e('🚗', ['car']),
  _e('🚘', ['oncoming automobile']),
  _e('🚙', ['blue car']),
  _e('🛻', ['pickup truck']),
  _e('🚚', ['delivery truck']),
  _e('🚛', ['semi truck']),
  _e('🚜', ['tractor']),
]

const OBJECTS_RAW: EmojiEntry[] = [
  _e('⌚', ['watch', 'time']),
  _e('📱', ['mobile phone', 'cell phone', 'phone', 'smartphone']),
  _e('📲', ['calling', 'phone with arrow']),
  _e('☎️', ['telephone']),
  _e('📞', ['telephone receiver']),
  _e('📟', ['pager']),
  _e('📠', ['fax']),
  _e('🔋', ['battery']),
  _e('🪫', ['low battery']),
  _e('🔌', ['electric plug']),
  _e('💻', ['laptop', 'computer', 'macbook', 'pc']),
  _e('🖥️', ['desktop computer', 'monitor']),
  _e('🖨️', ['printer']),
  _e('⌨️', ['keyboard']),
  _e('🖱️', ['computer mouse']),
  _e('🖲️', ['trackball']),
  _e('💽', ['computer disk']),
  _e('💾', ['floppy disk', 'save']),
  _e('💿', ['optical disk', 'cd']),
  _e('📀', ['dvd']),
  _e('🧮', ['abacus']),
  _e('🎥', ['movie camera', 'film', 'video']),
  _e('🎞️', ['film frames']),
  _e('📽️', ['film projector']),
  _e('🎬', ['clapper board']),
  _e('📺', ['television', 'tv']),
  _e('📷', ['camera', 'photo']),
  _e('📸', ['camera with flash']),
  _e('📹', ['video camera']),
  _e('📼', ['videocassette']),
  _e('🔍', ['magnifying glass tilted left']),
  _e('🔎', ['magnifying glass tilted right']),
  _e('🕯️', ['candle']),
  _e('💡', ['light bulb', 'idea', 'bright', 'innovation']),
  _e('🔦', ['flashlight', 'torch']),
  _e('🏮', ['red paper lantern']),
  _e('🪔', ['diya lamp']),
  _e('📔', ['notebook with decorative cover']),
  _e('📕', ['closed book']),
  _e('📖', ['open book']),
  _e('📗', ['green book']),
  _e('📘', ['blue book']),
  _e('📙', ['orange book']),
  _e('📚', ['books']),
  _e('📓', ['notebook']),
  _e('📒', ['ledger']),
  _e('📃', ['page with curl']),
  _e('📜', ['scroll']),
  _e('📄', ['page facing up']),
  _e('📰', ['newspaper']),
  _e('🗞️', ['rolled up newspaper']),
  _e('📑', ['bookmark tabs']),
  _e('🔖', ['bookmark']),
  _e('🏷️', ['label']),
  _e('💰', ['money bag', 'dollar', 'rich']),
  _e('🪙', ['coin']),
  _e('💴', ['yen banknote']),
  _e('💵', ['dollar bill', 'money']),
  _e('💶', ['euro banknote']),
  _e('💷', ['pound banknote']),
  _e('💸', ['money with wings', 'spending']),
  _e('💳', ['credit card', 'payment']),
  _e('🧾', ['receipt']),
  _e('💎', ['gem stone', 'diamond', 'jewel']),
  _e('⚖️', ['balance scale', 'justice']),
  _e('🧰', ['toolbox']),
  _e('🪜', ['ladder']),
  _e('🔧', ['wrench', 'spanner']),
  _e('🔨', ['hammer', 'tool']),
  _e('⚒️', ['hammer and pick']),
  _e('🛠️', ['hammer and wrench']),
  _e('🪓', ['axe']),
  _e('⛏️', ['pick']),
  _e('🪚', ['carpentry saw']),
  _e('🔩', ['nut and bolt']),
  _e('⚙️', ['gear', 'settings', 'cog']),
  _e('🗜️', ['clamp']),
  _e('⚖️', ['balance scale']),
  _e('🦯', ['white cane']),
  _e('🔗', ['link']),
  _e('⛓️', ['chains']),
  _e('🧲', ['magnet']),
  _e('🪝', ['hook']),
  _e('🧺', ['basket']),
  _e('🧻', ['toilet paper']),
  _e('🪣', ['bucket']),
  _e('🧴', ['lotion bottle']),
  _e('🧼', ['soap']),
  _e('🫧', ['bubbles']),
  _e('🧽', ['sponge']),
  _e('🪥', ['toothbrush']),
  _e('🪤', ['mouse trap']),
  _e('🪆', ['nesting dolls']),
  _e('🚬', ['cigarette', 'smoking']),
  _e('⚰️', ['coffin', 'death']),
  _e('⚱️', ['funeral urn']),
  _e('🏺', ['amphora', 'jar']),
  _e('🗺️', ['world map']),
  _e('🧭', ['compass']),
  _e('🗿', ['moai', 'easter island', 'tiki']),
  _e('🪧', ['placard']),
  _e('🪪', ['identification card']),
  _e('🏧', ['atm sign']),
  _e('🚮', ['litter in bin']),
  _e('🚰', ['potable water']),
  _e('♿', ['wheelchair symbol']),
  _e('🚹', ['men sign']),
  _e('🚺', ['women sign']),
  _e('🚻', ['restroom']),
  _e('🚼', ['baby symbol']),
  _e('🚾', ['water closet']),
  _e('🛂', ['passport control']),
  _e('🛃', ['customs']),
  _e('🛄', ['baggage claim']),
  _e('🛅', ['left luggage']),
  _e('⚠️', ['warning']),
  _e('🚸', ['children crossing']),
  _e('⛔', ['no entry']),
  _e('🚫', ['prohibited']),
  _e('🚳', ['no bicycles']),
  _e('🚭', ['no smoking']),
  _e('🚯', ['no littering']),
  _e('🚱', ['non potable water']),
  _e('🚷', ['no pedestrians']),
  _e('📵', ['no mobile phones']),
  _e('🔞', ['no one under eighteen']),
  _e('☢️', ['radioactive']),
  _e('☣️', ['biohazard']),
  _e('⬆️', ['up arrow']),
  _e('↗️', ['up right arrow']),
  _e('➡️', ['right arrow']),
  _e('↘️', ['down right arrow']),
  _e('⬇️', ['down arrow']),
  _e('↙️', ['down left arrow']),
  _e('⬅️', ['left arrow']),
  _e('↖️', ['up left arrow']),
  _e('↕️', ['up down arrow']),
  _e('↔️', ['left right arrow']),
  _e('↩️', ['right arrow curving left']),
  _e('↪️', ['left arrow curving right']),
  _e('⤴️', ['right arrow curving up']),
  _e('⤵️', ['right arrow curving down']),
  _e('🔃', ['clockwise vertical arrows']),
  _e('🔄', ['counterclockwise arrows']),
  _e('🔙', ['back arrow']),
  _e('🔚', ['end arrow']),
  _e('🔛', ['on arrow']),
  _e('🔜', ['soon arrow']),
  _e('🔝', ['top arrow']),
  _e('🛐', ['place of worship']),
  _e('⚛️', ['atom symbol']),
  _e('🕉️', ['om']),
  _e('✡️', ['star of david']),
  _e('☸️', ['dharma wheel']),
  _e('☯️', ['yin yang']),
  _e('✝️', ['latin cross']),
  _e('☦️', ['orthodox cross']),
  _e('☪️', ['star and crescent']),
  _e('☮️', ['peace symbol']),
  _e('🕎', ['menorah']),
  _e('🔯', ['six pointed star']),
  _e('🪯', ['khanda']),
]

const SYMBOLS_RAW: EmojiEntry[] = [
  _e('❤️', ['red heart', 'love', 'heart']),
  _e('🩷', ['pink heart']),
  _e('🧡', ['orange heart']),
  _e('💛', ['yellow heart']),
  _e('💚', ['green heart']),
  _e('💙', ['blue heart']),
  _e('🩵', ['light blue heart']),
  _e('💜', ['purple heart']),
  _e('🖤', ['black heart']),
  _e('🩶', ['grey heart']),
  _e('🤍', ['white heart']),
  _e('🤎', ['brown heart']),
  _e('💔', ['broken heart', 'heartbreak']),
  _e('❤️‍🔥', ['heart on fire']),
  _e('❤️‍🩹', ['mending heart']),
  _e('💕', ['two hearts']),
  _e('💞', ['revolving hearts']),
  _e('💓', ['beating heart', 'heartbeat']),
  _e('💗', ['growing heart']),
  _e('💖', ['sparkling heart']),
  _e('💘', ['heart with arrow', 'cupid']),
  _e('💝', ['heart with ribbon', 'gift']),
  _e('💟', ['heart decoration']),
  _e('❣️', ['heart exclamation']),
  _e('💔', ['broken heart']),
  _e('💯', ['hundred points', 'perfect', '100']),
  _e('💢', ['anger symbol']),
  _e('💥', ['collision', 'boom']),
  _e('💫', ['dizzy']),
  _e('💦', ['sweat droplets']),
  _e('💨', ['dashing away']),
  _e('🕳️', ['hole']),
  _e('💬', ['speech balloon']),
  _e('👁️‍🗨️', ['eye in speech bubble']),
  _e('🗨️', ['left speech bubble']),
  _e('🗯️', ['right anger bubble']),
  _e('💭', ['thought balloon']),
  _e('💤', ['zzz', 'sleeping']),
  _e('✅', ['check mark', 'done', 'complete', 'yes', 'approved']),
  _e('☑️', ['ballot box with check', 'checked']),
  _e('✔️', ['heavy check mark']),
  _e('❌', ['cross mark', 'no', 'wrong']),
  _e('❎', ['cross mark button']),
  _e('➕', ['plus', 'add']),
  _e('➖', ['minus', 'subtract']),
  _e('➗', ['divide', 'division']),
  _e('✖️', ['multiplication', 'multiply']),
  _e('♾️', ['infinity']),
  _e('‼️', ['double exclamation']),
  _e('⁉️', ['exclamation question']),
  _e('❓', ['question mark', 'red question']),
  _e('❔', ['white question mark']),
  _e('❕', ['white exclamation mark']),
  _e('❗', ['exclamation mark', 'red exclamation', 'important']),
  _e('〰️', ['wavy dash']),
  _e('|', ['vertical bar']),
  _e('💱', ['currency exchange']),
  _e('💲', ['heavy dollar sign', 'money']),
  _e('⚕️', ['medical symbol']),
  _e('♻️', ['recycling', 'environment']),
  _e('⚜️', ['fleur de lis']),
  _e('🔱', ['trident emblem']),
  _e('📛', ['name badge']),
  _e('🔰', ['japanese symbol for beginner']),
  _e('⭕', ['hollow red circle', 'done']),
  _e('㊗️', ['congratulations']),
  _e('㊙️', ['secret']),
  _e('🟠', ['orange circle']),
  _e('🟡', ['yellow circle']),
  _e('🟢', ['green circle']),
  _e('🔵', ['blue circle']),
  _e('🟣', ['purple circle']),
  _e('🟤', ['brown circle']),
  _e('⚫', ['black circle']),
  _e('⚪', ['white circle']),
  _e('🟥', ['red square']),
  _e('🟧', ['orange square']),
  _e('🟨', ['yellow square']),
  _e('🟩', ['green square']),
  _e('🟦', ['blue square']),
  _e('🟪', ['purple square']),
  _e('🟫', ['brown square']),
  _e('⬛', ['black large square']),
  _e('⬜', ['white large square']),
  _e('◼️', ['black medium square']),
  _e('◻️', ['white medium square']),
  _e('◾', ['black medium small square']),
  _e('◽', ['white medium small square']),
  _e('▪️', ['black small square']),
  _e('▫️', ['white small square']),
  _e('🔶', ['large orange diamond']),
  _e('🔷', ['large blue diamond']),
  _e('🔸', ['small orange diamond']),
  _e('🔹', ['small blue diamond']),
  _e('🔺', ['red triangle pointed up']),
  _e('🔻', ['red triangle pointed down']),
  _e('💠', ['diamond with a dot']),
  _e('🔘', ['radio button']),
  _e('🔳', ['white square button']),
  _e('🔲', ['black square button']),
  // Emojis & Symbols
  _e('🔀', ['shuffle', 'random', 'twisted arrows']),
  _e('🔁', ['repeat', 'loop', 'repeat all']),
  _e('🔂', ['repeat single', 'loop one']),
  _e('▶️', ['play', 'triangle']),
  _e('⏩', ['fast forward']),
  _e('⏭️', ['next track']),
  _e('⏯️', ['play or pause']),
  _e('◀️', ['reverse']),
  _e('⏪', ['rewind']),
  _e('⏮️', ['previous track']),
  _e('🔼', ['up button']),
  _e('⏫', ['fast up']),
  _e('🔽', ['down button']),
  _e('⏬', ['fast down']),
  _e('⏸️', ['pause']),
  _e('⏹️', ['stop']),
  _e('⏺️', ['record']),
  _e('⏏️', ['eject']),
  _e('🎦', ['cinema']),
  _e('🔅', ['dim button']),
  _e('🔆', ['bright button']),
  _e('📶', ['antenna bars']),
  _e('🛜', ['wireless']),
  _e('📳', ['vibration mode']),
  _e('📴', ['mobile phone off']),
  _e('♀️', ['female sign']),
  _e('♂️', ['male sign']),
  _e('⚧️', ['transgender sign']),
  _e('✖️', ['multiplication x']),
  _e('➕', ['heavy plus sign']),
  _e('➖', ['heavy minus sign']),
  _e('➗', ['heavy division sign']),
  _e('🟰', ['heavy equals sign']),
  _e('♾️', ['infinity']),
  _e('‼️', ['double exclamation mark']),
  _e('⁉️', ['exclamation question mark']),
  _e('❓', ['red question mark']),
  _e('❔', ['white question mark']),
  _e('❕', ['white exclamation mark']),
  _e('❗', ['exclamation mark', 'red exclamation']),
  _e('〰️', ['wavy dash']),
  _e('💱', ['currency exchange']),
  _e('💲', ['heavy dollar sign']),
  _e('⚕️', ['medical symbol']),
  _e('♻️', ['recycling symbol']),
  _e('⚜️', ['fleur de lis']),
  _e('🔱', ['trident emblem']),
  _e('📛', ['name badge']),
  _e('🔰', ['japanese symbol for beginner']),
  _e('⭕', ['hollow red circle']),
  _e('❇️', ['sparkle']),
  _e('✳️', ['eight spoked asterisk']),
  _e('✴️', ['eight pointed star']),
  _e('❇️', ['sparkle']),
  _e('💹', ['chart increasing with yen']),
  _e('🅴', ['squared e']),
  _e('🆓', ['squared free']),
  _e('🆕', ['squared new']),
  _e('🆖', ['squared ng']),
  _e('🆗', ['squared ok']),
  _e('🆙', ['squared up']),
  _e('🆒', ['squared cool']),
  _e('🆓', ['squared free']),
  _e('🎦', ['cinema']),
  _e('🆔', ['squared id']),
  _e('Ⓜ️', ['circled m']),
  _e('🆕', ['new button']),
  _e('🆖', ['ng button']),
  _e('🆗', ['ok button']),
  _e('🅿️', ['parking button']),
  _e('🆙', ['up button']),
  _e('🆚', ['vs button']),
  _e('🈁', ['japanese here button']),
  _e('🈂️', ['japanese service charge button']),
  _e('🈷️', ['japanese monthly amount button']),
  _e('🈶', ['japanese not free of charge button']),
  _e('🈯', ['japanese reserved button']),
  _e('🉐', ['japanese bargain button']),
  _e('🈹', ['japanese discount button']),
  _e('🈚', ['japanese free of charge button']),
  _e('🈲', ['japanese prohibited button']),
  _e('🉑', ['japanese acceptable button']),
  _e('🈸', ['japanese application button']),
  _e('🈴', ['japanese passing grade button']),
  _e('🈳', ['japanese vacancy button']),
  _e('㊗️', ['japanese congratulations button']),
  _e('㊙️', ['japanese secret button']),
  _e('🈺', ['japanese open for business button']),
  _e('🈵', ['japanese no vacancy button']),
  _e('🔴', ['red circle']),
  _e('🟠', ['orange circle']),
  _e('🟡', ['yellow circle']),
  _e('🟢', ['green circle']),
  _e('🔵', ['blue circle']),
  _e('🟣', ['purple circle']),
  _e('🟤', ['brown circle']),
  _e('⚫', ['black circle']),
  _e('⚪', ['white circle']),
  _e('🟥', ['red square']),
  _e('🟧', ['orange square']),
  _e('🟨', ['yellow square']),
  _e('🟩', ['green square']),
  _e('🟦', ['blue square']),
  _e('🟪', ['purple square']),
  _e('🟫', ['brown square']),
  _e('⬛', ['black large square']),
  _e('⬜', ['white large square']),
  _e('◼️', ['black medium square']),
  _e('◻️', ['white medium square']),
  _e('◾', ['black medium small square']),
  _e('◽', ['white medium small square']),
  _e('▪️', ['black small square']),
  _e('▫️', ['white small square']),
  _e('🔶', ['large orange diamond']),
  _e('🔷', ['large blue diamond']),
  _e('🔸', ['small orange diamond']),
  _e('🔹', ['small blue diamond']),
  _e('🔺', ['red triangle pointed up']),
  _e('🔻', ['red triangle pointed down']),
  _e('💠', ['diamond with a dot']),
  _e('🔘', ['radio button']),
  _e('🔳', ['white square button']),
  _e('🔲', ['black square button']),
]

const FLAGS_RAW: EmojiEntry[] = [
  _e('🏁', ['chequered flag', 'racing', 'finish']),
  _e('🚩', ['red flag', 'warning']),
  _e('🎌', ['crossed flags', 'japanese']),
  _e('🏴', ['black flag']),
  _e('🏳️', ['white flag']),
  _e('🏳️‍🌈', ['rainbow flag', 'pride', 'lgbtq']),
  _e('🏳️‍⚧️', ['transgender flag']),
  _e('🏴‍☠️', ['pirate flag']),
  _e('🇺🇸', ['united states flag', 'america', 'us', 'usa']),
  _e('🇬🇧', ['united kingdom flag', 'uk', 'britain', 'england']),
  _e('🇨🇳', ['china flag']),
  _e('🇯🇵', ['japan flag']),
  _e('🇰🇷', ['south korea flag']),
  _e('🇩🇪', ['germany flag']),
  _e('🇫🇷', ['france flag']),
  _e('🇮🇹', ['italy flag']),
  _e('🇪🇸', ['spain flag']),
  _e('🇧🇷', ['brazil flag']),
  _e('🇷🇺', ['russia flag']),
  _e('🇮🇳', ['india flag']),
  _e('🇨🇦', ['canada flag']),
  _e('🇦🇺', ['australia flag']),
  _e('🇲🇽', ['mexico flag']),
  _e('🇹🇷', ['turkey flag']),
  _e('🇸🇦', ['saudi arabia flag']),
  _e('🇦🇪', ['united arab emirates flag']),
  _e('🇮🇩', ['indonesia flag']),
  _e('🇵🇰', ['pakistan flag']),
  _e('🇳🇬', ['nigeria flag']),
  _e('🇵🇭', ['philippines flag']),
  _e('🇪🇬', ['egypt flag']),
  _e('🇻🇳', ['vietnam flag']),
  _e('🇹🇭', ['thailand flag']),
  _e('🇵🇱', ['poland flag']),
  _e('🇳🇱', ['netherlands flag']),
  _e('🇧🇪', ['belgium flag']),
  _e('🇨🇭', ['switzerland flag']),
  _e('🇸🇪', ['sweden flag']),
  _e('🇳🇴', ['norway flag']),
  _e('🇩🇰', ['denmark flag']),
  _e('🇫🇮', ['finland flag']),
  _e('🇮🇪', ['ireland flag']),
  _e('🇵🇹', ['portugal flag']),
  _e('🇬🇷', ['greece flag']),
  _e('🇮🇱', ['israel flag']),
  _e('🇺🇦', ['ukraine flag']),
  _e('🇦🇷', ['argentina flag']),
  _e('🇨🇴', ['colombia flag']),
  _e('🇨🇱', ['chile flag']),
  _e('🇵🇪', ['peru flag']),
  _e('🇿🇦', ['south africa flag']),
  _e('🇰🇪', ['kenya flag']),
  _e('🇪🇹', ['ethiopia flag']),
  _e('🇬🇭', ['ghana flag']),
  _e('🇹🇿', ['tanzania flag']),
  _e('🇲🇦', ['morocco flag']),
  _e('🇳🇿', ['new zealand flag']),
  _e('🇸🇬', ['singapore flag']),
  _e('🇲🇾', ['malaysia flag']),
  _e('🇮🇷', ['iran flag']),
  _e('🇮🇶', ['iraq flag']),
  _e('🇮🇸', ['iceland flag']),
  _e('🇨🇺', ['cuba flag']),
  _e('🇬🇹', ['guatemala flag']),
  _e('🇭🇳', ['honduras flag']),
  _e('🇪🇨', ['ecuador flag']),
  _e('🇧🇴', ['bolivia flag']),
  _e('🇻🇪', ['venezuela flag']),
  _e('🇨🇷', ['costa rica flag']),
  _e('🇵🇦', ['panama flag']),
  _e('🇺🇾', ['uruguay flag']),
  _e('🇵🇾', ['paraguay flag']),
  _e('🇧🇸', ['bahamas flag']),
  _e('🇯🇲', ['jamaica flag']),
  _e('🇭🇹', ['haiti flag']),
  _e('🇩🇴', ['dominican republic flag']),
  _e('🇹🇹', ['trinidad and tobago flag']),
  _e('🇧🇧', ['barbados flag']),
  _e('🇬🇾', ['guyana flag']),
  _e('🇸🇷', ['suriname flag']),
  _e('🇧🇿', ['belize flag']),
  _e('🇳🇮', ['nicaragua flag']),
  _e('🇸🇻', ['el salvador flag']),
  _e('🇦🇹', ['austria flag']),
  _e('🇨🇿', ['czechia flag']),
  _e('🇸🇰', ['slovakia flag']),
  _e('🇭🇺', ['hungary flag']),
  _e('🇷🇴', ['romania flag']),
  _e('🇧🇬', ['bulgaria flag']),
  _e('🇭🇷', ['croatia flag']),
  _e('🇸🇮', ['slovenia flag']),
  _e('🇷🇸', ['serbia flag']),
  _e('🇲🇪', ['montenegro flag']),
  _e('🇧🇦', ['bosnia and herzegovina flag']),
  _e('🇦🇱', ['albania flag']),
  _e('🇲🇰', ['north macedonia flag']),
  _e('🇽🇰', ['kosovo flag']),
  _e('🇱🇺', ['luxembourg flag']),
  _e('🇲🇹', ['malta flag']),
  _e('🇨🇾', ['cyprus flag']),
  _e('🇪🇪', ['estonia flag']),
  _e('🇱🇻', ['latvia flag']),
  _e('🇱🇹', ['lithuania flag']),
  _e('🇦🇲', ['armenia flag']),
  _e('🇬🇪', ['georgia flag']),
  _e('🇦🇿', ['azerbaijan flag']),
  _e('🇰🇿', ['kazakhstan flag']),
  _e('🇺🇿', ['uzbekistan flag']),
  _e('🇹🇲', ['turkmenistan flag']),
  _e('🇰🇬', ['kyrgyzstan flag']),
  _e('🇹🇯', ['tajikistan flag']),
  _e('🇲🇳', ['mongolia flag']),
  _e('🇰🇵', ['north korea flag']),
  _e('🇹🇼', ['taiwan flag']),
  _e('🇭🇰', ['hong kong flag']),
  _e('🇲🇴', ['macao flag']),
  _e('🇦🇫', ['afghanistan flag']),
  _e('🇧🇩', ['bangladesh flag']),
  _e('🇱🇰', ['sri lanka flag']),
  _e('🇳🇵', ['nepal flag']),
  _e('🇧🇹', ['bhutan flag']),
  _e('🇲🇲', ['myanmar flag']),
  _e('🇰🇭', ['cambodia flag']),
  _e('🇱🇦', ['laos flag']),
  _e('🇧🇳', ['brunei flag']),
  _e('🇹🇱', ['timor leste flag']),
  _e('🇹🇴', ['tonga flag']),
  _e('🇫🇯', ['fiji flag']),
  _e('🇼🇸', ['samoa flag']),
  _e('🇵🇬', ['papua new guinea flag']),
  _e('🇦🇩', ['andorra flag']),
  _e('🇲🇨', ['monaco flag']),
  _e('🇱🇮', ['liechtenstein flag']),
  _e('🇸🇲', ['san marino flag']),
  _e('🇻🇦', ['vatican city flag']),
  _e('🇶🇦', ['qatar flag']),
  _e('🇧🇭', ['bahrain flag']),
  _e('🇰🇼', ['kuwait flag']),
  _e('🇴🇲', ['oman flag']),
  _e('🇯🇴', ['jordan flag']),
  _e('🇱🇧', ['lebanon flag']),
  _e('🇸🇾', ['syria flag']),
  _e('🇾🇪', ['yemen flag']),
  _e('🇮🇱', ['israel flag']),
  _e('🇵🇸', ['palestinian territories flag']),
  _e('🇨🇳', ['china flag']),
  _e('🇯🇵', ['japan flag']),
  _e('🇰🇷', ['south korea flag']),
  _e('🇲🇳', ['mongolia flag']),
  _e('🇰🇿', ['kazakhstan flag']),
  _e('🇺🇿', ['uzbekistan flag']),
  _e('🇹🇲', ['turkmenistan flag']),
  _e('🇰🇬', ['kyrgyzstan flag']),
  _e('🇹🇯', ['tajikistan flag']),
  _e('🇦🇫', ['afghanistan flag']),
  _e('🇵🇰', ['pakistan flag']),
  _e('🇮🇳', ['india flag']),
  _e('🇧🇩', ['bangladesh flag']),
  _e('🇱🇰', ['sri lanka flag']),
  _e('🇳🇵', ['nepal flag']),
  _e('🇧🇹', ['bhutan flag']),
  _e('🇲🇲', ['myanmar flag']),
  _e('🇹🇭', ['thailand flag']),
  _e('🇱🇦', ['laos flag']),
  _e('🇰🇭', ['cambodia flag']),
  _e('🇻🇳', ['vietnam flag']),
  _e('🇲🇾', ['malaysia flag']),
  _e('🇸🇬', ['singapore flag']),
  _e('🇮🇩', ['indonesia flag']),
  _e('🇧🇳', ['brunei flag']),
  _e('🇵🇭', ['philippines flag']),
  _e('🇹🇱', ['timor leste flag']),
  _e('🇪🇬', ['egypt flag']),
  _e('🇱🇾', ['libya flag']),
  _e('🇹🇳', ['tunisia flag']),
  _e('🇩🇿', ['algeria flag']),
  _e('🇲🇦', ['morocco flag']),
  _e('🇸🇩', ['sudan flag']),
  _e('🇸🇸', ['south sudan flag']),
  _e('🇪🇹', ['ethiopia flag']),
  _e('🇸🇴', ['somalia flag']),
  _e('🇩🇯', ['djibouti flag']),
  _e('🇪🇷', ['eritrea flag']),
  _e('🇰🇪', ['kenya flag']),
  _e('🇺🇬', ['uganda flag']),
  _e('🇷🇼', ['rwanda flag']),
  _e('🇧🇮', ['burundi flag']),
  _e('🇹🇿', ['tanzania flag']),
  _e('🇨🇩', ['democratic republic of the congo flag']),
  _e('🇨🇬', ['republic of the congo flag']),
  _e('🇬🇦', ['gabon flag']),
  _e('🇬🇶', ['equatorial guinea flag']),
  _e('🇨🇲', ['cameroon flag']),
  _e('🇳🇬', ['nigeria flag']),
  _e('🇧🇯', ['benin flag']),
  _e('🇹🇬', ['togo flag']),
  _e('🇬🇭', ['ghana flag']),
  _e('🇨🇮', ['ivory coast flag']),
  _e('🇱🇷', ['liberia flag']),
  _e('🇸🇱', ['sierra leone flag']),
  _e('🇬🇳', ['guinea flag']),
  _e('🇬🇼', ['guinea bissau flag']),
  _e('🇬🇲', ['gambia flag']),
  _e('🇸🇳', ['senegal flag']),
  _e('🇲🇱', ['mali flag']),
  _e('🇧🇫', ['burkina faso flag']),
  _e('🇳🇪', ['niger flag']),
  _e('🇹🇩', ['chad flag']),
  _e('🇨🇫', ['central african republic flag']),
  _e('🇨🇲', ['cameroon flag']),
  _e('🇿🇦', ['south africa flag']),
  _e('🇳🇦', ['namibia flag']),
  _e('🇧🇼', ['botswana flag']),
  _e('🇿🇼', ['zimbabwe flag']),
  _e('🇿🇲', ['zambia flag']),
  _e('🇲🇼', ['malawi flag']),
  _e('🇲🇿', ['mozambique flag']),
  _e('🇦🇴', ['angola flag']),
  _e('🇸🇿', ['eswatini flag']),
  _e('🇱🇸', ['lesotho flag']),
  _e('🇲🇬', ['madagascar flag']),
  _e('🇲🇺', ['mauritius flag']),
  _e('🇸🇨', ['seychelles flag']),
  _e('🇰🇲', ['comoros flag']),
  _e('🇲🇻', ['maldives flag']),
  _e('🇦🇷', ['argentina flag']),
  _e('🇧🇴', ['bolivia flag']),
  _e('🇧🇷', ['brazil flag']),
  _e('🇨🇱', ['chile flag']),
  _e('🇨🇴', ['colombia flag']),
  _e('🇪🇨', ['ecuador flag']),
  _e('🇫🇰', ['falkland islands flag']),
  _e('🇬🇫', ['french guiana flag']),
  _e('🇬🇾', ['guyana flag']),
  _e('🇵🇪', ['peru flag']),
  _e('🇵🇾', ['paraguay flag']),
  _e('🇸🇷', ['suriname flag']),
  _e('🇺🇾', ['uruguay flag']),
  _e('🇻🇪', ['venezuela flag']),
  _e('🇦🇮', ['anguilla flag']),
  _e('🇦🇬', ['antigua and barbuda flag']),
  _e('🇦🇼', ['aruba flag']),
  _e('🇧🇸', ['bahamas flag']),
  _e('🇧🇧', ['barbados flag']),
  _e('🇧🇿', ['belize flag']),
  _e('🇧🇲', ['bermuda flag']),
  _e('🇻🇬', ['british virgin islands flag']),
  _e('🇰🇾', ['cayman islands flag']),
  _e('🇨🇺', ['cuba flag']),
  _e('🇨🇼', ['curacao flag']),
  _e('🇩🇲', ['dominica flag']),
  _e('🇩🇴', ['dominican republic flag']),
  _e('🇬🇩', ['grenada flag']),
  _e('🇬🇵', ['guadeloupe flag']),
  _e('🇭🇹', ['haiti flag']),
  _e('🇯🇲', ['jamaica flag']),
  _e('🇲🇶', ['martinique flag']),
  _e('🇵🇷', ['puerto rico flag']),
  _e('🇰🇳', ['st kitts and nevis flag']),
  _e('🇱🇨', ['st lucia flag']),
  _e('🇻🇨', ['st vincent and the grenadines flag']),
  _e('🇹🇹', ['trinidad and tobago flag']),
  _e('🇻🇮', ['us virgin islands flag']),
  _e('🇨🇦', ['canada flag']),
  _e('🇬🇱', ['greenland flag']),
  _e('🇲🇽', ['mexico flag']),
  _e('🇧🇿', ['belize flag']),
  _e('🇨🇷', ['costa rica flag']),
  _e('🇸🇻', ['el salvador flag']),
  _e('🇬🇹', ['guatemala flag']),
  _e('🇭🇳', ['honduras flag']),
  _e('🇳🇮', ['nicaragua flag']),
  _e('🇵🇦', ['panama flag']),
  _e('🇺🇸', ['united states flag']),
  _e('🇺🇲', ['us outlying islands flag']),
  _e('🇦🇸', ['american samoa flag']),
  _e('🇬🇺', ['guam flag']),
  _e('🇲🇵', ['northern mariana islands flag']),
  _e('🇻🇮', ['us virgin islands flag']),
  _e('🇦🇺', ['australia flag']),
  _e('🇨🇽', ['christmas island flag']),
  _e('🇨🇨', ['cocos islands flag']),
  _e('🇳🇿', ['new zealand flag']),
  _e('🇨🇰', ['cook islands flag']),
  _e('🇳🇺', ['niue flag']),
  _e('🇵🇬', ['papua new guinea flag']),
  _e('🇫🇯', ['fiji flag']),
  _e('🇵🇫', ['french polynesia flag']),
  _e('🇼🇸', ['samoa flag']),
  _e('🇹🇴', ['tonga flag']),
  _e('🇹🇻', ['tuvalu flag']),
  _e('🇻🇺', ['vanuatu flag']),
  _e('🇫🇲', ['micronesia flag']),
  _e('🇰🇮', ['kiribati flag']),
  _e('🇲🇭', ['marshall islands flag']),
  _e('🇳🇷', ['nauru flag']),
  _e('🇵🇼', ['palau flag']),
  _e('🇦🇺', ['australia flag']),
  _e('🇦🇹', ['austria flag']),
  _e('🇧🇪', ['belgium flag']),
  _e('🇧🇬', ['bulgaria flag']),
  _e('🇭🇷', ['croatia flag']),
  _e('🇨🇾', ['cyprus flag']),
  _e('🇨🇿', ['czechia flag']),
  _e('🇩🇰', ['denmark flag']),
  _e('🇪🇪', ['estonia flag']),
  _e('🇫🇮', ['finland flag']),
  _e('🇫🇷', ['france flag']),
  _e('🇩🇪', ['germany flag']),
  _e('🇬🇷', ['greece flag']),
  _e('🇭🇺', ['hungary flag']),
  _e('🇮🇪', ['ireland flag']),
  _e('🇮🇹', ['italy flag']),
  _e('🇱🇻', ['latvia flag']),
  _e('🇱🇹', ['lithuania flag']),
  _e('🇱🇺', ['luxembourg flag']),
  _e('🇲🇹', ['malta flag']),
  _e('🇳🇱', ['netherlands flag']),
  _e('🇵🇱', ['poland flag']),
  _e('🇵🇹', ['portugal flag']),
  _e('🇷🇴', ['romania flag']),
  _e('🇸🇰', ['slovakia flag']),
  _e('🇸🇮', ['slovenia flag']),
  _e('🇪🇸', ['spain flag']),
  _e('🇸🇪', ['sweden flag']),
  _e('🇬🇧', ['united kingdom flag']),
  _e('🇪🇺', ['european union flag']),
  _e('🇧🇱', ['st barthelemy flag']),
  _e('🇵🇲', ['st pierre and miquelon flag']),
  _e('🇬🇸', ['south georgia flag']),
  _e('🇸🇯', ['svalbard flag']),
  _e('🇧🇻', ['bouvet island flag']),
  _e('🇦🇨', ['ascension island flag']),
  _e('🇮🇲', ['isle of man flag']),
  _e('🇬🇬', ['guernsey flag']),
  _e('🇯🇪', ['jersey flag']),
  _e('🇫🇴', ['faroe islands flag']),
  _e('🇦🇽', ['aland islands flag']),
  _e('🇮🇨', ['canary islands flag']),
  _e('🇬🇪', ['georgia flag']),
  _e('🇦🇲', ['armenia flag']),
  _e('🇦🇿', ['azerbaijan flag']),
  _e('🇨🇵', ['clipperton island flag']),
  _e('🇪🇦', ['ceuta and melilla flag']),
  _e('🇲🇫', ['st martin flag']),
  _e('🇧🇶', ['caribbean netherlands flag']),
  _e('🇳🇫', ['norfolk island flag']),
  _e('🇭🇲', ['heard island and mcdonald islands flag']),
  _e('🇰🇲', ['comoros flag']),
  _e('🇲🇬', ['madagascar flag']),
  _e('🇲🇼', ['malawi flag']),
  _e('🇲🇿', ['mozambique flag']),
  _e('🇳🇪', ['niger flag']),
  _e('🇷🇪', ['reunion flag']),
  _e('🇸🇹', ['sao tome and principe flag']),
  _e('🇹🇩', ['chad flag']),
  _e('🇾🇹', ['mayotte flag']),
  _e('🇿🇲', ['zambia flag']),
  _e('🇿🇼', ['zimbabwe flag']),
  _e('🇦🇴', ['angola flag']),
  _e('🇧🇼', ['botswana flag']),
  _e('🇱🇸', ['lesotho flag']),
  _e('🇳🇦', ['namibia flag']),
  _e('🇸🇿', ['eswatini flag']),
  _e('🇹🇿', ['tanzania flag']),
  _e('🇺🇬', ['uganda flag']),
  _e('🇿🇦', ['south africa flag']),
  _e('🇧🇮', ['burundi flag']),
  _e('🇰🇲', ['comoros flag']),
  _e('🇩🇯', ['djibouti flag']),
  _e('🇪🇷', ['eritrea flag']),
  _e('🇪🇹', ['ethiopia flag']),
  _e('🇰🇪', ['kenya flag']),
  _e('🇰🇲', ['comoros flag']),
  _e('🇲🇬', ['madagascar flag']),
  _e('🇲🇺', ['mauritius flag']),
  _e('🇲🇿', ['mozambique flag']),
  _e('🇷🇼', ['rwanda flag']),
  _e('🇸🇨', ['seychelles flag']),
  _e('🇸🇴', ['somalia flag']),
  _e('🇹🇿', ['tanzania flag']),
  _e('🇺🇬', ['uganda flag']),
  _e('🇿🇲', ['zambia flag']),
  _e('🇿🇼', ['zimbabwe flag']),
  _e('🇹🇱', ['timor leste flag']),
  _e('🇵🇼', ['palau flag']),
  _e('🇲🇭', ['marshall islands flag']),
  _e('🇫🇲', ['micronesia flag']),
  _e('🇰🇮', ['kiribati flag']),
  _e('🇳🇷', ['nauru flag']),
  _e('🇵🇬', ['papua new guinea flag']),
  _e('🇸🇧', ['solomon islands flag']),
  _e('🇻🇺', ['vanuatu flag']),
  _e('🇳🇺', ['niue flag']),
  _e('🇵🇲', ['st pierre and miquelon flag']),
  _e('🇽🇰', ['kosovo flag']),
  _e('🇦🇨', ['ascension island flag']),
  _e('🇦🇩', ['andorra flag']),
  _e('🇦🇪', ['united arab emirates flag']),
  _e('🇦🇫', ['afghanistan flag']),
  _e('🇦🇬', ['antigua and barbuda flag']),
  _e('🇦🇮', ['anguilla flag']),
  _e('🇦🇱', ['albania flag']),
  _e('🇦🇲', ['armenia flag']),
  _e('🇦🇴', ['angola flag']),
  _e('🇦🇶', ['antarctica flag']),
  _e('🇦🇷', ['argentina flag']),
  _e('🇦🇸', ['american samoa flag']),
  _e('🇦🇹', ['austria flag']),
  _e('🇦🇺', ['australia flag']),
  _e('🇦🇼', ['aruba flag']),
  _e('🇦🇽', ['aland islands flag']),
  _e('🇦🇿', ['azerbaijan flag']),
  _e('🇧🇦', ['bosnia and herzegovina flag']),
  _e('🇧🇧', ['barbados flag']),
  _e('🇧🇩', ['bangladesh flag']),
  _e('🇧🇪', ['belgium flag']),
  _e('🇧🇫', ['burkina faso flag']),
  _e('🇧🇬', ['bulgaria flag']),
  _e('🇧🇭', ['bahrain flag']),
  _e('🇧🇮', ['burundi flag']),
  _e('🇧🇯', ['benin flag']),
  _e('🇧🇱', ['st barthelemy flag']),
  _e('🇧🇲', ['bermuda flag']),
  _e('🇧🇳', ['brunei flag']),
  _e('🇧🇴', ['bolivia flag']),
  _e('🇧🇶', ['caribbean netherlands flag']),
  _e('🇧🇷', ['brazil flag']),
  _e('🇧🇸', ['bahamas flag']),
  _e('🇧🇹', ['bhutan flag']),
  _e('🇧🇻', ['bouvet island flag']),
  _e('🇧🇼', ['botswana flag']),
  _e('🇧🇾', ['belarus flag']),
  _e('🇧🇿', ['belize flag']),
  _e('🇨🇦', ['canada flag']),
  _e('🇨🇨', ['cocos islands flag']),
  _e('🇨🇩', ['democratic republic of the congo flag']),
  _e('🇨🇫', ['central african republic flag']),
  _e('🇨🇬', ['republic of the congo flag']),
  _e('🇨🇭', ['switzerland flag']),
  _e('🇨🇮', ['ivory coast flag']),
  _e('🇨🇰', ['cook islands flag']),
  _e('🇨🇱', ['chile flag']),
  _e('🇨🇲', ['cameroon flag']),
  _e('🇨🇳', ['china flag']),
  _e('🇨🇴', ['colombia flag']),
  _e('🇨🇵', ['clipperton island flag']),
  _e('🇨🇷', ['costa rica flag']),
  _e('🇨🇺', ['cuba flag']),
  _e('🇨🇻', ['cape verde flag']),
  _e('🇨🇼', ['curacao flag']),
  _e('🇨🇽', ['christmas island flag']),
  _e('🇨🇾', ['cyprus flag']),
  _e('🇨🇿', ['czechia flag']),
  _e('🇩🇪', ['germany flag']),
  _e('🇩🇬', ['diego garcia flag']),
  _e('🇩🇯', ['djibouti flag']),
  _e('🇩🇰', ['denmark flag']),
  _e('🇩🇲', ['dominica flag']),
  _e('🇩🇴', ['dominican republic flag']),
  _e('🇩🇿', ['algeria flag']),
  _e('🇪🇦', ['ceuta and melilla flag']),
  _e('🇪🇨', ['ecuador flag']),
  _e('🇪🇪', ['estonia flag']),
  _e('🇪🇬', ['egypt flag']),
  _e('🇪🇭', ['western sahara flag']),
  _e('🇪🇷', ['eritrea flag']),
  _e('🇪🇸', ['spain flag']),
  _e('🇪🇹', ['ethiopia flag']),
  _e('🇪🇺', ['european union flag']),
  _e('🇫🇮', ['finland flag']),
  _e('🇫🇯', ['fiji flag']),
  _e('🇫🇰', ['falkland islands flag']),
  _e('🇫🇲', ['micronesia flag']),
  _e('🇫🇴', ['faroe islands flag']),
  _e('🇫🇷', ['france flag']),
  _e('🇬🇦', ['gabon flag']),
  _e('🇬🇧', ['united kingdom flag', 'uk', 'britain']),
  _e('🇬🇩', ['grenada flag']),
  _e('🇬🇪', ['georgia flag']),
  _e('🇬🇫', ['french guiana flag']),
  _e('🇬🇬', ['guernsey flag']),
  _e('🇬🇭', ['ghana flag']),
  _e('🇬🇮', ['gibraltar flag']),
  _e('🇬🇱', ['greenland flag']),
  _e('🇬🇲', ['gambia flag']),
  _e('🇬🇳', ['guinea flag']),
  _e('🇬🇵', ['guadeloupe flag']),
  _e('🇬🇶', ['equatorial guinea flag']),
  _e('🇬🇷', ['greece flag']),
  _e('🇬🇸', ['south georgia and south sandwich islands flag']),
  _e('🇬🇹', ['guatemala flag']),
  _e('🇬🇺', ['guam flag']),
  _e('🇬🇼', ['guinea bissau flag']),
  _e('🇬🇾', ['guyana flag']),
  _e('🇭🇰', ['hong kong flag']),
  _e('🇭🇲', ['heard island and mcdonald islands flag']),
  _e('🇭🇳', ['honduras flag']),
  _e('🇭🇷', ['croatia flag']),
  _e('🇭🇹', ['haiti flag']),
  _e('🇭🇺', ['hungary flag']),
  _e('🇮🇨', ['canary islands flag']),
  _e('🇮🇩', ['indonesia flag']),
  _e('🇮🇪', ['ireland flag']),
  _e('🇮🇱', ['israel flag']),
  _e('🇮🇲', ['isle of man flag']),
  _e('🇮🇳', ['india flag']),
  _e('🇮🇴', ['british indian ocean territory flag']),
  _e('🇮🇶', ['iraq flag']),
  _e('🇮🇷', ['iran flag']),
  _e('🇮🇸', ['iceland flag']),
  _e('🇮🇹', ['italy flag']),
  _e('🇯🇪', ['jersey flag']),
  _e('🇯🇲', ['jamaica flag']),
  _e('🇯🇴', ['jordan flag']),
  _e('🇯🇵', ['japan flag']),
  _e('🇰🇪', ['kenya flag']),
  _e('🇰🇬', ['kyrgyzstan flag']),
  _e('🇰🇭', ['cambodia flag']),
  _e('🇰🇮', ['kiribati flag']),
  _e('🇰🇲', ['comoros flag']),
  _e('🇰🇳', ['st kitts and nevis flag']),
  _e('🇰🇵', ['north korea flag']),
  _e('🇰🇷', ['south korea flag']),
  _e('🇰🇼', ['kuwait flag']),
  _e('🇰🇾', ['cayman islands flag']),
  _e('🇰🇿', ['kazakhstan flag']),
  _e('🇱🇦', ['laos flag']),
  _e('🇱🇧', ['lebanon flag']),
  _e('🇱🇨', ['st lucia flag']),
  _e('🇱🇮', ['liechtenstein flag']),
  _e('🇱🇰', ['sri lanka flag']),
  _e('🇱🇷', ['liberia flag']),
  _e('🇱🇸', ['lesotho flag']),
  _e('🇱🇹', ['lithuania flag']),
  _e('🇱🇺', ['luxembourg flag']),
  _e('🇱🇻', ['latvia flag']),
  _e('🇱🇾', ['libya flag']),
  _e('🇲🇦', ['morocco flag']),
  _e('🇲🇨', ['monaco flag']),
  _e('🇲🇩', ['moldova flag']),
  _e('🇲🇪', ['montenegro flag']),
  _e('🇲🇫', ['st martin flag']),
  _e('🇲🇬', ['madagascar flag']),
  _e('🇲🇭', ['marshall islands flag']),
  _e('🇲🇰', ['north macedonia flag']),
  _e('🇲🇱', ['mali flag']),
  _e('🇲🇲', ['myanmar flag']),
  _e('🇲🇳', ['mongolia flag']),
  _e('🇲🇴', ['macao flag']),
  _e('🇲🇵', ['northern mariana islands flag']),
  _e('🇲🇶', ['martinique flag']),
  _e('🇲🇷', ['mauritania flag']),
  _e('🇲🇸', ['montserrat flag']),
  _e('🇲🇹', ['malta flag']),
  _e('🇲🇺', ['mauritius flag']),
  _e('🇲🇻', ['maldives flag']),
  _e('🇲🇼', ['malawi flag']),
  _e('🇲🇽', ['mexico flag']),
  _e('🇲🇾', ['malaysia flag']),
  _e('🇲🇿', ['mozambique flag']),
  _e('🇳🇦', ['namibia flag']),
  _e('🇳🇨', ['new caledonia flag']),
  _e('🇳🇪', ['niger flag']),
  _e('🇳🇫', ['norfolk island flag']),
  _e('🇳🇬', ['nigeria flag']),
  _e('🇳🇮', ['nicaragua flag']),
  _e('🇳🇱', ['netherlands flag']),
  _e('🇳🇴', ['norway flag']),
  _e('🇳🇵', ['nepal flag']),
  _e('🇳🇷', ['nauru flag']),
  _e('🇳🇺', ['niue flag']),
  _e('🇳🇿', ['new zealand flag']),
  _e('🇴🇲', ['oman flag']),
  _e('🇵🇦', ['panama flag']),
  _e('🇵🇪', ['peru flag']),
  _e('🇵🇫', ['french polynesia flag']),
  _e('🇵🇬', ['papua new guinea flag']),
  _e('🇵🇭', ['philippines flag']),
  _e('🇵🇰', ['pakistan flag']),
  _e('🇵🇱', ['poland flag']),
  _e('🇵🇲', ['st pierre and miquelon flag']),
  _e('🇵🇳', ['pitcairn islands flag']),
  _e('🇵🇷', ['puerto rico flag']),
  _e('🇵🇸', ['palestinian territories flag']),
  _e('🇵🇹', ['portugal flag']),
  _e('🇵🇼', ['palau flag']),
  _e('🇵🇾', ['paraguay flag']),
  _e('🇶🇦', ['qatar flag']),
  _e('🇷🇪', ['reunion flag']),
  _e('🇷🇴', ['romania flag']),
  _e('🇷🇸', ['serbia flag']),
  _e('🇷🇺', ['russia flag']),
  _e('🇷🇼', ['rwanda flag']),
  _e('🇸🇦', ['saudi arabia flag']),
  _e('🇸🇧', ['solomon islands flag']),
  _e('🇸🇨', ['seychelles flag']),
  _e('🇸🇩', ['sudan flag']),
  _e('🇸🇪', ['sweden flag']),
  _e('🇸🇬', ['singapore flag']),
  _e('🇸🇭', ['st helena flag']),
  _e('🇸🇮', ['slovenia flag']),
  _e('🇸🇯', ['svalbard and jan mayen flag']),
  _e('🇸🇰', ['slovakia flag']),
  _e('🇸🇱', ['sierra leone flag']),
  _e('🇸🇲', ['san marino flag']),
  _e('🇸🇳', ['senegal flag']),
  _e('🇸🇴', ['somalia flag']),
  _e('🇿🇦', ['south africa flag']),
  _e('🇬🇸', ['south georgia flag']),
  _e('🇰🇷', ['south korea flag']),
  _e('🇸🇸', ['south sudan flag']),
  _e('🇪🇸', ['spain flag']),
  _e('🇱🇰', ['sri lanka flag']),
  _e('🇸🇩', ['sudan flag']),
  _e('🇸🇷', ['suriname flag']),
  _e('🇸🇯', ['svalbard flag']),
  _e('🇸🇪', ['sweden flag']),
  _e('🇨🇭', ['switzerland flag']),
  _e('🇸🇾', ['syria flag']),
  _e('🇹🇼', ['taiwan flag']),
  _e('🇹🇯', ['tajikistan flag']),
  _e('🇹🇿', ['tanzania flag']),
  _e('🇹🇭', ['thailand flag']),
  _e('🇹🇱', ['timor leste flag']),
  _e('🇹🇬', ['togo flag']),
  _e('🇹🇰', ['tokelau flag']),
  _e('🇹🇴', ['tonga flag']),
  _e('🇹🇹', ['trinidad and tobago flag']),
  _e('🇹🇳', ['tunisia flag']),
  _e('🇹🇷', ['turkey flag']),
  _e('🇹🇲', ['turkmenistan flag']),
  _e('🇹🇨', ['turks and caicos islands flag']),
  _e('🇹🇻', ['tuvalu flag']),
  _e('🇺🇬', ['uganda flag']),
  _e('🇺🇦', ['ukraine flag']),
  _e('🇦🇪', ['united arab emirates flag']),
  _e('🇬🇧', ['united kingdom flag']),
  _e('🇺🇲', ['us outlying islands flag']),
  _e('🇺🇸', ['united states flag', 'america', 'us', 'usa']),
  _e('🇺🇾', ['uruguay flag']),
  _e('🇺🇿', ['uzbekistan flag']),
  _e('🇻🇦', ['vatican city flag']),
  _e('🇻🇨', ['st vincent and the grenadines flag']),
  _e('🇻🇪', ['venezuela flag']),
  _e('🇻🇬', ['british virgin islands flag']),
  _e('🇻🇮', ['us virgin islands flag']),
  _e('🇻🇳', ['vietnam flag']),
  _e('🇻🇺', ['vanuatu flag']),
  _e('🇼🇫', ['wallis and futuna flag']),
  _e('🇼🇸', ['samoa flag']),
  _e('🇽🇰', ['kosovo flag']),
  _e('🇾🇪', ['yemen flag']),
  _e('🇾🇹', ['mayotte flag']),
  _e('🇿🇦', ['south africa flag']),
  _e('🇿🇲', ['zambia flag']),
  _e('🇿🇼', ['zimbabwe flag']),
]

/* ─── Build database ─── */

const CATEGORY_MAP: [EmojiEntry[], EmojiCategory][] = [
  [SMILEYS_RAW, 'smileys'],
  [PEOPLE_RAW, 'people'],
  [NATURE_RAW, 'nature'],
  [FOOD_RAW, 'food'],
  [ACTIVITIES_RAW, 'activities'],
  [TRAVEL_RAW, 'travel'],
  [OBJECTS_RAW, 'objects'],
  [SYMBOLS_RAW, 'symbols'],
  [FLAGS_RAW, 'flags'],
]

export const EMOJI_DATABASE: EmojiEntry[] = CATEGORY_MAP.flatMap(([entries, category]) =>
  entries.map((e) => ({ ...e, category })),
)

export function getEmojisByCategory(category: EmojiCategory): EmojiEntry[] {
  return EMOJI_DATABASE.filter((e) => e.category === category)
}

export function getCategoryCounts(): Record<EmojiCategory, number> {
  const counts = {} as Record<EmojiCategory, number>
  for (const cat of EMOJI_CATEGORIES) {
    counts[cat.key] = EMOJI_DATABASE.filter((e) => e.category === cat.key).length
  }
  return counts
}

export function getEmojiWithSkinTone(emoji: string, skinTone: string): string {
  return emoji + skinTone
}
