import { zip } from '@/utils/crypto'

export interface TemplateItem {
  id: number
  preview: string
  width: number
  height: number
  data: string
  title: string
  text: string
  images?: string
}

/**
 * Template metadata for quick loading
 * This file is automatically generated by scanning the templates directory
 */
interface TemplateMetadata {
  id: number
  title: string
  text: string
  preview: string
  width: number
  height: number
  filename: string
}

/**
 * Load all available templates from the local templates directory
 */
export async function loadTemplatesList(): Promise<TemplateItem[]> {
  try {
    // Import the templates index which lists all available templates
    const templatesIndex = await loadTemplatesIndex()
    
    // Convert metadata to TemplateItem format
    const templates: TemplateItem[] = templatesIndex.map(meta => ({
      id: meta.id,
      title: meta.title,
      text: meta.text,
      preview: meta.preview,
      width: meta.width,
      height: meta.height,
      data: '', // Data will be loaded on demand
      images: meta.preview
    }))
    
    return templates
  } catch (error) {
    console.error('Failed to load templates list:', error)
    return []
  }
}

/**
 * Load a specific template's full data by ID
 */
export async function loadTemplateData(id: number): Promise<TemplateItem | null> {
  try {
    const templatesIndex = await loadTemplatesIndex()
    const templateMeta = templatesIndex.find(t => t.id === id)
    
    if (!templateMeta) {
      console.error(`Template with ID ${id} not found`)
      return null
    }
    
    // Load the full template JSON file
    const response = await fetch(`./templates/${templateMeta.filename}`)
    if (!response.ok) {
      throw new Error(`Failed to load template: ${response.statusText}`)
    }
    
    const templateData = await response.json()
    
    // Compress the data field as the system expects
    const compressedData = zip(JSON.stringify(templateData.data))
    
    return {
      id: templateData.id,
      title: templateData.title,
      text: templateData.text,
      preview: templateData.preview,
      width: templateData.width,
      height: templateData.height,
      data: compressedData,
      images: templateData.preview
    }
  } catch (error) {
    console.error(`Failed to load template data for ID ${id}:`, error)
    return null
  }
}

/**
 * Load the templates index which contains metadata for all templates
 * This scans the templates directory and builds the index dynamically
 */
async function loadTemplatesIndex(): Promise<TemplateMetadata[]> {
  try {
    // Try to load the auto-generated index first
    const indexResponse = await fetch('./templates/index.json')
    if (indexResponse.ok) {
      const index = await indexResponse.json()
      return index.templates
    }
  } catch (error) {
    console.warn('Templates index not found, scanning directory...', error)
  }
  
  // Fallback: manually scan known templates
  // In production, you should generate index.json during build
  const knownTemplates = [
    'blank.json',
    'presentation-slide.json',
    'social-media-post.json'
  ]
  
  const templates: TemplateMetadata[] = []
  
  for (const filename of knownTemplates) {
    try {
      const response = await fetch(`./templates/${filename}`)
      if (response.ok) {
        const data = await response.json()
        templates.push({
          id: data.id,
          title: data.title,
          text: data.text,
          preview: data.preview,
          width: data.width,
          height: data.height,
          filename: filename
        })
      }
    } catch (error) {
      console.warn(`Failed to load template ${filename}:`, error)
    }
  }
  
  return templates
}

/**
 * Paginate templates for UI display
 */
export function paginateTemplates(
  templates: TemplateItem[],
  page: number,
  size: number
): {
  items: TemplateItem[]
  total: number
  pages: number
  page: number
} {
  const start = (page - 1) * size
  const end = start + size
  const items = templates.slice(start, end)
  
  return {
    items,
    total: templates.length,
    pages: Math.ceil(templates.length / size),
    page
  }
}
