// Lucide Vue Next Icons
// https://lucide.dev/icons/

import { App } from 'vue'
import {
  Play,
  Maximize2,
  Lock,
  Unlock,
  Presentation,
  FileType,
  Image,
  Maximize,
  List,
  ListOrdered,
  HelpCircle,
  FlipVertical,
  FlipHorizontal,
  Type,
  Code,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Edit,
  Quote,
  PaintBucket,
  Group,
  Ungroup,
  ArrowLeft,
  ArrowRight,
  Maximize2 as Fullwidth,
  AlignVerticalJustifyStart,
  AlignHorizontalJustifyStart,
  AlignHorizontalJustifyEnd,
  AlignVerticalJustifyEnd,
  AlignVerticalJustifyCenter,
  AlignHorizontalJustifyCenter,
  BringToFront,
  SendToBack,
  AlignLeft,
  AlignRight,
  AlignCenter,
  AlignVerticalDistributeCenter,
  Pencil,
  Type as AddText,
  PaintBucket as Fill,
  Scissors,
  Wand2,
  Settings,
  Palette,
  ArrowUp,
  ArrowDown,
  Plus,
  Minus,
  Link2,
  BringToFront as BringToFrontOne,
  SendToBack as SentToBack,
  Github,
  PieChart,
  BarChart3,
  BarChart4,
  AreaChart,
  PieChart as Doughnut,
  ScatterChart,
  LineChart,
  PieChart as ChartPie,
  Type as Text,
  RotateCw,
  ChevronsLeft,
  ChevronsRight,
  Palette as Platte,
  X,
  X as CloseSmall,
  Undo2,
  Move,
  MousePointer,
  Palette as Theme,
  ArrowLeftCircle,
  Palette as GraphicDesign,
  LogOut,
  Eraser,
  Trash2,
  Folder,
  AlignVerticalJustifyStart as AlignTextTopOne,
  AlignVerticalJustifyEnd as AlignTextBottomOne,
  AlignVerticalJustifyCenter as AlignTextMiddleOne,
  Pause,
  VolumeX,
  Volume2,
  Volume1,
  Video,
  Calculator,
  Link,
  Maximize as FullScreenOne,
  Minimize,
  Power,
  LayoutList,
  Wand2 as Magic,
  Highlighter,
  Share2,
  IndentDecrease,
  IndentIncrease,
  MoveVertical,
  Copy,
  Trash2 as Delete,
  Square,
  Circle,
  Triangle,
  RotateCcw,
  RotateCw as TextRotationDown,
  Brush,
  Eye,
  EyeOff,
  Timer,
  Shuffle,
  Minimize2,
  QrCode,
  MoreHorizontal,
  SquareKanban,
  Layout,
  Shapes,
  ChevronLeft,
  ChevronRight,
  BookOpen,
  Keyboard,
  Headphones,
  Menu,
  EyeOff as PreviewCloseOne,
  Upload,
  Layers,
  AlignCenter as AlignTextCenterOne,
  RefreshCw,
  Users,
  ScreenShare,
  Upload as UploadOne,
  Download,
  Save,
  Shield,
  Scissors as CuttingOne,
  Ruler,
  CreditCard,
  ChevronDown,
  ChevronUp,
  MousePointerClick,
  Type as AddTextTwo,
  Check,
  Barcode,
  QrCode as PayCodeTwo,
  Type as TextStyleOne,
  Combine as Intersect,
  SendToBack as SendBackward,
  BringToFront as BringForward,
  Combine,
  Plus as Union,
  Minimize2 as ExcludeSelection,
  Minus as SubtractSelection,
  Minus as SubtractSelectionOne,
  Grid3x3,
  Home,
  Plus as Newlybuild,
  Minus as DividingLine,
  AlignJustify,
  Slice,
  Languages,
  Wand2 as MagicWand,
  Heading1,
  Heading3,
  ArrowLeftRight,
  Menu as HamburgerButton,
  Contrast,
  MoveUp,
  MoveDown,
  MoveUp as RightSmallUp,
  MoveDown as RightSmallDown,
  Map,
  ChevronRight as RightC,
  ChevronLeft as LeftC,
  ChevronRight as RightOne,
  ChevronDown as DownOne,
  Copy as CopyOne,
  MessageCircle,
  MessageSquare,
  Mail,
  Share2 as ShareOne,
  Navigation,
  LayoutList as ViewList,
  Sigma,
  Frame
} from 'lucide-vue-next'

export const icons = {
  IconPlayOne: Play,
  IconFullScreenPlay: Maximize2,
  IconLock: Lock,
  IconUnlock: Unlock,
  IconPpt: Presentation,
  IconFormat: FileType,
  IconPicture: Image,
  IconFullScreen: Maximize,
  IconList: List,
  IconOrderedList: ListOrdered,
  IconHelpcenter: HelpCircle,
  IconFlipVertically: FlipVertical,
  IconFlipHorizontally: FlipHorizontal,
  IconFontSize: Type,
  IconCode: Code,
  IconTextBold: Bold,
  IconTextItalic: Italic,
  IconTextUnderline: Underline,
  IconStrikethrough: Strikethrough,
  IconEdit: Edit,
  IconQuote: Quote,
  IconBackgroundColor: PaintBucket,
  IconGroup: Group,
  IconUngroup: Ungroup,
  IconBack: ArrowLeft,
  IconNext: ArrowRight,
  IconFullwidth: Fullwidth,
  IconAlignTop: AlignVerticalJustifyStart,
  IconAlignLeft: AlignHorizontalJustifyStart,
  IconAlignRight: AlignHorizontalJustifyEnd,
  IconAlignBottom: AlignVerticalJustifyEnd,
  IconAlignVertically: AlignVerticalJustifyCenter,
  IconAlignHorizontally: AlignHorizontalJustifyCenter,
  IconBringToFront: BringToFront,
  IconSendToBack: SendToBack,
  IconAlignTextLeft: AlignLeft,
  IconAlignTextRight: AlignRight,
  IconAlignTextCenter: AlignCenter,
  IconRowHeight: AlignVerticalDistributeCenter,
  IconWrite: Pencil,
  IconAddText: AddText,
  IconFill: Fill,
  IconTailoring: Scissors,
  IconEffects: Wand2,
  IconColorFilter: Palette,
  IconUp: ArrowUp,
  IconDown: ArrowDown,
  IconPlus: Plus,
  IconMinus: Minus,
  IconConnection: Link2,
  IconBringToFrontOne: BringToFrontOne,
  IconSentToBack: SentToBack,
  IconGithub: Github,
  IconChartProportion: PieChart,
  IconChartHistogram: BarChart3,
  IconChartHistogramOne: BarChart4,
  IconChartLineArea: AreaChart,
  IconChartRing: Doughnut,
  IconChartScatter: ScatterChart,
  IconChartLine: LineChart,
  IconChartPie: ChartPie,
  IconText: Text,
  IconRotate: RotateCw,
  IconLeftTwo: ChevronsLeft,
  IconRightTwo: ChevronsRight,
  IconPlatte: Platte,
  IconClose: X,
  IconCloseSmall: CloseSmall,
  IconUndo: Undo2,
  IconTransform: Move,
  IconClick: MousePointer,
  IconTheme: Theme,
  IconArrowCircleLeft: ArrowLeftCircle,
  IconGraphicDesign: GraphicDesign,
  IconLogout: LogOut,
  IconErase: Eraser,
  IconClear: Trash2,
  IconFolderClose: Folder,
  IconAlignTextTopOne: AlignTextTopOne,
  IconAlignTextBottomOne: AlignTextBottomOne,
  IconAlignTextMiddleOne: AlignTextMiddleOne,
  IconPause: Pause,
  IconVolumeMute: VolumeX,
  IconVolumeNotice: Volume2,
  IconVolumeSmall: Volume1,
  IconVideoTwo: Video,
  IconFormula: Calculator,
  IconLinkOne: Link,
  IconFullScreenOne: FullScreenOne,
  IconOffScreenOne: Minimize,
  IconPower: Power,
  IconListView: LayoutList,
  IconMagic: Magic,
  IconHighLight: Highlighter,
  IconShare: Share2,
  IconIndentLeft: IndentDecrease,
  IconIndentRight: IndentIncrease,
  IconVerticalSpacingBetweenItems: MoveVertical,
  IconCopy: Copy,
  IconDelete: Delete,
  IconSquare: Square,
  IconRound: Circle,
  IconNeedle: Triangle,
  IconTextRotationNone: RotateCcw,
  IconTextRotationDown: TextRotationDown,
  IconFormatBrush: Brush,
  IconPreviewOpen: Eye,
  IconPreviewClose: EyeOff,
  IconStopwatchStart: Timer,
  IconShuffleOne: Shuffle,
  IconReduceOne: Minimize2,
  IconTwoDimensionalCodeTwo: QrCode,
  IconMore: MoreHorizontal,
  IconRightAngle: SquareKanban,
  IconPageTemplate: Layout,
  IconTriangleRoundRectangle: Shapes,
  IconLeft: ChevronLeft,
  IconRight: ChevronRight,
  IconGuideBoard: BookOpen,
  IconKeyboardOne: Keyboard,
  IconHeadsetOne: Headphones,
  IconApplicationMenu: Menu,
  IconPreviewCloseOne: PreviewCloseOne,
  IconUpload: Upload,
  IconLayers: Layers,
  IconAlignTextCenterOne: AlignTextCenterOne,
  IconRefresh: RefreshCw,
  IconPeoples: Users,
  IconScreenRotation: ScreenShare,
  IconUploadOne: UploadOne,
  IconDownloadOne: Download,
  IconSave: Save,
  IconShield: Shield,
  IconCuttingOne: CuttingOne,
  IconRuler: Ruler,
  IconIdCard: CreditCard,
  IconExpandDownOne: ChevronDown,
  IconFoldUpOne: ChevronUp,
  IconClickTap: MousePointerClick,
  IconAddTextTwo: AddTextTwo,
  IconCheckOne: Check,
  IconBarCode: Barcode,
  IconPayCodeTwo: PayCodeTwo,
  IconTextStyleOne: TextStyleOne,
  IconIntersection: Intersect,
  IconSendBackward: SendBackward,
  IconBringForward: BringForward,
  IconIntersectSelection: Combine,
  IconUnionSelection: Union,
  IconExcludeSelection: ExcludeSelection,
  IconSubtractSelection: SubtractSelection,
  IconSubtractSelectionOne: SubtractSelectionOne,
  IconAllApplication: Grid3x3,
  IconHome: Home,
  IconNewlybuild: Newlybuild,
  IconDividingLine: DividingLine,
  IconAlignTextBoth: AlignJustify,
  IconDistortion: Slice,
  IconTranslate: Languages,
  IconMagicWand: MagicWand,
  IconH1: Heading1,
  IconH3: Heading3,
  IconTransferData: ArrowLeftRight,
  IconHamburgerButton: HamburgerButton,
  IconContrastViewCircle: Contrast,
  IconLeftSmallUp: MoveUp,
  IconLeftSmallDown: MoveDown,
  IconRightSmallUp: RightSmallUp,
  IconRightSmallDown: RightSmallDown,
  IconMapDraw: Map,
  IconFrame: Frame,
  IconRightC: RightC,
  IconLeftC: LeftC,
  IconRightOne: RightOne,
  IconDownOne: DownOne,
  IconCopyOne: CopyOne,
  IconWechat: MessageCircle,
  IconTencentQq: MessageSquare,
  IconMail: Mail,
  IconShareOne: ShareOne,
  IconNavigation: Navigation,
  IconViewList: ViewList,
  IconMathFormula: Sigma,
  IconSettings: Settings
}

export default {
  install(app: App) {
  for (const [key, component] of Object.entries(icons))
    app.component(key, component)
  }
}